### ISSUE TITLE
There are some quality issues for contributing to this project

### ISSUE THREAD

**Issue by coderpatros** [actions/setup-dotnet#103]
### Description

I'm filling out a bug report apparently. But it is just general feedback. Although maybe a "bug" in the documentation :)

### Details

I read [contributors.md](https://raw.githubusercontent.com/actions/setup-dotnet/master/docs/contributors.md). But my PR #25  appears to be failing because of linting checks.

I'm not in the typescript world so this might be typescript 101 stuff. In which case feel free to close this issue. But I think there could be a bit more added to the doco from what is included in the github workflow you run.

**Comment by ZEisinger** [comment]
I have updated the docs with some more details. Thanks for bringing this up, there had been some changes around this action that were not documented yet. 61ee7d7a725c2cfa5abf018fd6b3d351aeac3452
