### ISSUE TITLE
Add an option to pass includePrerelease to semver

### ISSUE THREAD

**Issue by GGG-KILLER** [actions/setup-dotnet#105]
### Description
I'd like to suggest an option to be able to pass `includePrerelease: true` (to disable the [default behavior](https://github.com/npm/node-semver#prerelease-tags) in `semver`) on the `semver.satisfies` calls (and any other `semver` call) done in `installer.ts`:
https://github.com/actions/setup-dotnet/blob/7df9f59802b508a78c4e4e0f48c27ed646a9158c/src/installer.ts#L294-L305

### Details
This would enable anyone to get the latest preview version of, for example, .NET 5.0 with the `5`, `5.0`, `5.*`, `5.x`, `5.0.*` or `5.0.x` patterns (tested locally with `semver` 7.3.2 and node.js v14.2.0):
```
> semver.satisfies("5.0.0-preview.6", "5.0.*")
false
> semver.satisfies("5.0.0-preview.6", "5.0.*", {includePrerelease: true})
true
```
The [default behavior](https://github.com/npm/node-semver#prerelease-tags) in `semver` makes it so that prerelease tags aren't matched by `semver.satisfies` unless you pass the same exact version (making wildcards useless for prerelease matching purposes).
The default behavior would be the current one (`includePrerelease: false`) to avoid breaking changes.

I would be willing to work on a PR however I created this issue to obtain feedback before I put in any work into it.

**Comment by ZEisinger** [comment]
Hey @GGG-KILLER, This would be a great feature to include! @litetex recently added the feature to choose the latest version using semver and added some quality tests with those changes (these would be good models to follow): #82 
Also, I just updated https://github.com/actions/setup-dotnet/blob/main/docs/contributors.md with some details about how to test and run updates for changes.

It seems like you have a good idea of how to implement this. Making a flag named includePrerelease in the action.yml file would be a good way to specify the input (default of 'false', 'true' can be opted into). Feel free to create an early PR for feedback as you work on this.
