### ISSUE TITLE
dotnet version is not working correctly with windows_latest

### ISSUE THREAD

**Issue by rogerbriggen** [actions/setup-dotnet#106]
### Description

I have a matrix with windows-latest and ubuntu-latest. ubuntu works, windows has no errors but does not use the specified version of dotnet

### Details

build.yml to reproduce (check ubuntu which uses the given version in the last step. windows uses the latest one even dotnet_root is set correct). Maybe its also an Windows-Image problem.

    name: CI
    
    on: [push]
    
    jobs:
      build:
        name: build
        runs-on: ${{ matrix.operating-system }}
        strategy:
          matrix:
            operating-system: [windows-latest, ubuntu-latest] 
           
        steps:
    
          - name: Checkout
            uses: actions/checkout@master
    
    
          - name: Setup dotnet env
            uses: actions/setup-dotnet@v1
            with:
                dotnet-version: '3.1.100' # SDK Version to use. 
    
    
          - name: Build projects
            run: dotnet --version

**Comment by ZEisinger** [comment]
Hey @rogerbriggen, I suspect this is related to the flag `DOTNET_MULTILEVEL_LOOKUP`. Windows is the only OS where this defaults to true, and as a result the global install location will be used if there are installed versions. Can you try setting that flag to false: https://github.com/actions/setup-dotnet#environment-variables-to-use-with-dotnet?
Please reopen if you continue to have a problem with this.
