### ISSUE TITLE
remove erroneous tags

### ISSUE THREAD

**Issue by adamralph** [actions/setup-dotnet#107]
There seem to be two erroneous tags:

- https://github.com/actions/setup-dotnet/releases/tag/v1 - on the same commit as the correct tag `v1.5.0`.
- https://github.com/actions/setup-dotnet/releases/tag/1.4.0 - on the same commit as the correct tag `v1.4.0`.

**Comment by coderpatros** [comment]
Wouldn’t v1 always track the latest v1.x.x tag?

**Comment by ZEisinger** [comment]
I removed 1.4.0. As mentioned previously, v1 is the recommended tag to use at all times (and the one in the README).
