### ISSUE TITLE
DOTNET_ROOT for Global Tools

### ISSUE THREAD

**Issue by onovotny** [actions/setup-dotnet#11]
The DOTNET_ROOT environment variable needs to be set so that .NET Core global tools find the right locations:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreInstallerV1/dotnetcoreinstaller.ts

**Comment by damccorm** [comment]
Huh, could've sworn we already did this. I'll add a PR.

**Comment by rojepp** [comment]
I'm pretty sure I'm doing something wrong, but this is still an issue for me. I made a minimal repo here to reproduce: https://github.com/rojepp/dotnetsay. 

Am I mistaken in thinking a proper DOTNET_ROOT should solve this issue? 
I'm getting the following error when running a dotnet tool.

> A fatal error occurred, the required library libhostfxr.so could not be found.
