### ISSUE TITLE
Build failed with Packages.props in repo

### ISSUE THREAD

**Issue by callmewhy** [actions/setup-dotnet#113]
### Description

Build failed if there is a Packages.props in repo

### Details
My [PR](https://github.com/callmewhy/sanji/pull/1/checks?check_run_id=907278528) builds failed in github workflow but I can run the commands successfully in local environment.

How can I config the workflow to make GitHub Action works as expected?

Thanks

**Comment by callmewhy** [comment]
it works on windows-latest but failed on ubuntu-latest

**Comment by coderpatros** [comment]
I tried building it locally on Linux and it failed. It’s full framework isn’t it? I’m on my phone at the moment so can’t double check.

**Comment by callmewhy** [comment]
Hi coderpatros , what does full framework mean? I can build successfully on my windows PC and workflow with windows-latest. But cannot build it with ubuntu-latest. I don't know whether the .NET build SDK support CentralPackageVersions on linus.

**Comment by coderpatros** [comment]
I mean .NET framework vs .NET core. 

Towards the end of the output of the failed step there is something about the package being restored for .NET framework instead of core. I think it works on Windows because it is installed. But the full framework isn’t available on Linux.

**Comment by coderpatros** [comment]
But I could be mistaken. I don’t really do any dev on Windows these days.

**Comment by ZEisinger** [comment]
I think @coderpatros is correct, the documentation mentions a new package for Newtonsoft in version 3.0. https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#add-package-references-for-removed-assemblies

@timheuer if there is any further details on that.

**Comment by ZEisinger** [comment]
Closing this issue out. Feel free to reopen for issues with this action or reach-out to https://github.com/dotnet/runtime#filing-issues for framework issues.
