### ISSUE TITLE
preview version failed!

### ISSUE THREAD

**Issue by DreamEnderKing** [actions/setup-dotnet#119]
### Description
Installation failed

### Details
The 5.0.100 version(Preview) could not be installed.(ubuntu 18.04)

**Comment by NoNamePro0** [comment]
Check this Version out: `5.0.100-preview.2.20176.6`

[Latest Versions](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json)
[Suggested Issue](https://github.com/dotnet/runtime/issues/34699#issuecomment-611094892)

**Comment by ZEisinger** [comment]
@NoNamePro0 is correct, #110 should address this as well.
