### ISSUE TITLE
setup-dotnet in version 1.7.0 no longer works correctly for channel versions, such as 3.1 or 3.1.x

### ISSUE THREAD

**Issue by JustArchi** [actions/setup-dotnet#128]
### Description

`setup-dotnet` in version 1.7.0 no longer works correctly for channel versions, such as `3.1` or `3.1.x` (which is interpreted the same).

### Details

This is a regression. Version 1.6.0 is working fine. Example log output can be found **[here](https://github.com/JustArchiNET/ArchiSteamFarm/runs/1146057550#step:3:23)**

```
Run actions/setup-dotnet@v1
  with:
    dotnet-version: 3.1
  env:
    CONFIGURATION: Release
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_NOLOGO: 1
    DOTNET_SDK_VERSION: 3.1
    NET_CORE_VERSION: netcoreapp3.1
    NET_FRAMEWORK_VERSION: net48
    NODE_JS_VERSION: 12
    STEAM_TOKEN_DUMPER_NAME: ArchiSteamFarm.OfficialPlugins.SteamTokenDumper
    STEAM_TOKEN_DUMPER_TOKEN: ***
/Users/runner/work/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh --version 3.1
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1/dotnet-sdk-3.1-osx-x64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1/dotnet-sdk-3.1-osx-x64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1/dotnet-dev-osx-x64.3.1.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1/dotnet-dev-osx-x64.3.1.tar.gz
dotnet_install: Error: Could not find/download: `.NET Core SDK` with version = 3.1
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
##[error]The process '/Users/runner/work/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh' failed with exit code 1
```

Example yaml file can be found **[here](https://github.com/JustArchiNET/ArchiSteamFarm/blob/0351725d800e24cf421849170363c8f302355bd3/.github/workflows/ci.yml)**. **[Replacing](https://github.com/JustArchiNET/ArchiSteamFarm/commit/46d3360f8d811811b0c450aca6d9670ef109fe28)** `@v1` (which points to `1.7.0` as of today) with `@v1.6.0` fixes the issue, as can be verified **[here](https://github.com/JustArchiNET/ArchiSteamFarm/actions/runs/265755122)**.

Let me know if you need more info. Judging from how easily it regressed in my setup, I believe there shouldn't be too much trouble localizing the culprit. Thank you in advance for your interest.

**Comment by Shane32** [comment]
Breaks all my deployment scripts.  Considering that the "basic" sample in the readme file now is broken, there are probably hundreds or thousands of people with broken scripts.  This should probably be fixed or reverted to the prior version immediately.

**Comment by veilofsecurity** [comment]
Confirming all of our deployments are also broken now, commits this morning worked but latest ones failing.

**Comment by iris-hpaterson** [comment]
We've experienced this issue breaking the ${{ env.DOTNET_ROOT }} environment environment variable in Github Actions. The variable is either set empty or not set at all.

Actions provided by Microsoft Azure to deploy webapps depend on DOTNET_ROOT being set.

We've hotfixed by rolling back to v1.6.0.

**Comment by Hoopie** [comment]
> `setup-dotnet` no longer works on `ubuntu-latest`

Looks like the `ubuntu-latest` image (18.04.5 LTS) now contains the dotnet cli installed by default not requiring this action.
The `setup-dotnet` action however adds the _matchers_ to pull out annotations.

We got our builds running but removing this action BUT are no longer getting annotations generated from the cli output.

Would love a patch asap

ref:
- https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners
- https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md

**Comment by RomainMuller** [comment]
> Looks like the `ubuntu-latest` image (18.04.5 LTS) now contains the dotnet cli installed by default not requiring this action.

Well, *not requiring this action* **unless you need a different version of the dotnet cli**...

**Comment by ZEisinger** [comment]
I've reverted the tag update for v1 back to 1.6.0 and will investigate.
