### ISSUE TITLE
Feature Request: run tool-restore automatically

### ISSUE THREAD

**Issue by jasonkarns** [actions/setup-dotnet#132]
The first thing every workflow of mine does (using this action), is to run `dotnet tool restore`. It seems that would be a useful step to be taken automatically (by default) by this action as part of setup. I recognize there would be scenarios where that is _not_ desirable. But I wager that the vast majority of scenarios would benefit from it. So making it the default would benefit the majority while the minority of scenarios could opt-out.

**Comment by adamralph** [comment]
👎 I've never required `dotnet tool restore` and I don't to pay the overhead.

**Comment by adamralph** [comment]
Let me rewind: I disagree with this assertion:

> the vast majority of scenarios would benefit from it

What evidence is there that supports this?

My evidence to the contrary is that none of the personal, community, or commercial repos I work with require `dotnet tool restore`.

**Comment by RichiCoder1** [comment]
I just stumbled upon this as we use Cake and two other local dotnet tools. Would be great to have this be an automatic behavior.

Either a detection of `.config/dotnet-tools.json` or an opt in flag would be terrific and incur no overhead for anyone who doesn't use the tools manifest.
