### ISSUE TITLE
Install without full name for release candidate no longer works

### ISSUE THREAD

**Issue by GGG-KILLER** [actions/setup-dotnet#133]
### Description
Using `5.0.100-rc.1` as the version instead of `5.0.100-rc.1.20452.10` no longer works.

I wasn't able to pinpoint the issue as v1.6.0, v1.7.0 and v1.7.1 all fail to install it. It was working [a few days ago](https://github.com/GGG-KILLER/GUtils.NET/runs/1138128385) but [now it no longer works](https://github.com/GGG-KILLER/GParse/runs/1167638115).

I'm not sure if the issue is in the setup scripts or somewhere else.

**Comment by vsafonkin** [comment]
Hi @GGG-KILLER , looks like it stopped working for installer' scripts as the value of version is passed to them. Maybe it makes sense to open issue in [dotnet/install-scripts repo](https://github.com/dotnet/install-scripts).

**Comment by GGG-KILLER** [comment]
> Hi @GGG-KILLER , looks like it stopped working for installer' scripts as the value of version is passed to them. Maybe it makes sense to open issue in [dotnet/install-scripts repo](https://github.com/dotnet/install-scripts).

Right, but the logic that does `5.0.x` should also be able to handle this, shouldn't it?

**Comment by vsafonkin** [comment]
Yes, but now the task does not support finding pre-release version. I believe [your PR](https://github.com/actions/setup-dotnet/pull/110) will be merged soon and it will be work.
