### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by alexrosenfeld10** [actions/setup-dotnet#143]
### Description

I realize this isn't a bug, but I'm curious if anyone has already begun flipping this to support .NET 5.

### Details

From what I could tell from some quick reading of the repo it doesn't look like there are any major changes that will be required. Just curious if anyone has already begun / planned to make the changes needed for .NET 5 support here.

**Comment by miere43** [comment]
It's supported, use `dotnet-version: 5.0.100` (you can see latest SDK at https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json)

**Comment by alexrosenfeld10** [comment]
Oh, great, thanks!
