### ISSUE TITLE
dotnet restore is unable to find common .NET packages since switching to .NET 5.0

### ISSUE THREAD

**Issue by baehny** [actions/setup-dotnet#145]
### Description

I switched from .NET Core 3.1 to .NET 5 and since then the action fails to restore common .Net packages.

### Details

Error messages on installing dependencies "dotnet restore Project.sln". The error does not occur when the command is executed locally. No custom nuget repository is used and the packages should be available.
```
error NU1101: Unable to find package System.Memory. No packages exist with this id in source(s): github [/home/runner/work/Project/Project.sln]
error NU1101: Unable to find package System.Numerics.Vectors. No packages exist with this id in source(s): github [/home/runner/work/Project/Project.sln]
error NU1101: Unable to find package NETStandard.Library. No packages exist with this id in source(s): github [/home/runner/work/Project/Project.sln]
```

```
name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore Project.sln
    - name: Build
      run: dotnet build Project.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Project.sln --no-restore --verbosity normal
```

**Comment by Cyberboss** [comment]
Another: https://github.com/tgstation/tgstation-server/pull/1164/checks?check_run_id=1567700693

```
 D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Client\Tgstation.Server.Client.csproj : error NU1101: Unable to find package Microsoft.CodeAnalysis.NetAnalyzers. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tests\Tgstation.Server.Tests\Tgstation.Server.Tests.csproj]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Client\Tgstation.Server.Client.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Http.Extensions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tests\Tgstation.Server.Tests\Tgstation.Server.Tests.csproj]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Client\Tgstation.Server.Client.csproj : error NU1102: Unable to find package Newtonsoft.Json with version (>= 12.0.3) [D:\a\tgstation-server\tgstation-server\tests\Tgstation.Server.Tests\Tgstation.Server.Tests.csproj]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Client\Tgstation.Server.Client.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 9.0.1 ] [D:\a\tgstation-server\tgstation-server\tests\Tgstation.Server.Tests\Tgstation.Server.Tests.csproj]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Client\Tgstation.Server.Client.csproj : error NU1102: Unable to find package System.ComponentModel.Annotations with version (>= 5.0.0) [D:\a\tgstation-server\tgstation-server\tests\Tgstation.Server.Tests\Tgstation.Server.Tests.csproj]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Client\Tgstation.Server.Client.csproj : error NU1102:   - Found 2 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 4.1.0 ] [D:\a\tgstation-server\tgstation-server\tests\Tgstation.Server.Tests\Tgstation.Server.Tests.csproj]
```

**Comment by MohdmM01** [comment]
I am also experiencin gthis issue:

D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.Services\JM.Formox.Services.csproj : error NU1101: Unable to find package Azure.Messaging.EventHubs.Processor. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.MicroService.sln]
D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.Services\JM.Formox.Services.csproj : error NU1101: Unable to find package Microsoft.Extensions.Http. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.MicroService.sln]
D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.Services\JM.Formox.Services.csproj : error NU1101: Unable to find package Microsoft.IdentityModel.Clients.ActiveDirectory. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.MicroService.sln]

My action setup for dotnet up to the restore section:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Install dependencies
      run: dotnet restore

**Comment by csinkers** [comment]
Yup, sounds like my issue (155) is the same, but I'm seeing it on 3.1.100 so it's not just .NET 5. Looks like the action hasn't had any changes recently, so maybe an update in NuGet itself or something environmental with the build agent setup? Based on the message it sounds like the NuGet repository list ends up empty causing it to only use locally cached packages.

**Comment by csinkers** [comment]
Looks like adding a clean step before the build stops it happening, the comments on #155 have more details.

**Comment by vsafonkin** [comment]
Duplicate #155 , closed.

**Comment by csinkers** [comment]
The details for why it broke and why a nuget.config fixes it are pretty complicated, if you follow the links from this issue to the various ones that got raised in the github actions, .net core, and nuget repositories you can get the whole story. 

I think it boiled down to a change in some nuget rule that ended up (sporadically) breaking things for every project that didn't have an explicit nuget config, and while the nuget change would normally be benign, some detail of the GitHub actions environment meant it caused issues.

Because it was only partially the fault of either project I think neither took responsibility for fixing it, so we all have to be explicit about our nuget sources using a config now :/

**Comment by marijnz0r** [comment]
@csinkers Thanks so much for your answer. It took me 2 days to find this to be the solution.
Is there any way to write this down somewhere so people can find this in the future?
