### ISSUE TITLE
Consider Moving .NET SDK Installation to the Temp Drive on Public Runners

### ISSUE THREAD

**Issue by brianrob** [actions/setup-dotnet#150]
### Description

When a user installs a .NET SDK on the a Windows public runner during an Action, it is installed in %USERPROFILE%, which means that it is installed on the OS drive, which is heavily throttled.  On first launch, there are a significant number of hard faults because none of the files are in the file system cache, which results in I/O throttling, and noticeable increased latency.

### Proposal

Rather than installing the SDK on the OS drive, install the SDK on the temp drive by default.  The temp drive has higher I/O limits, which means that there will be less I/O throttling and lower execution latency.

cc: @rsemenov

**Comment by rsemenov** [comment]
Looks like https://github.com/actions/setup-dotnet/blob/main/externals/install-dotnet.ps1 already has `InstallDir` parameter. We need to decide how to update the action to maintain compatibility for the users that rely on SDK being installed in the current location. The versioning doc https://github.com/actions/toolkit/blob/main/docs/action-versioning.md says 

>Introduce a major version for compatibility breaks and major rewrites of the action.

To avoid major version release we can maintain compatibility by exposing `InstallDir` as an optional parameter. And later when we ready to release a major version we can update the default install path.

@StanleyGoldman for feedback on this

**Comment by brianrob** [comment]
Thanks much @rsemenov.  @StanleyGoldman what do you think?

**Comment by AraHaan** [comment]
I would actually prefer installing it like now, but instead cache it, I personally want it cached myself so then ``setup-dotnet`` becomes a hot path and then all it would need to do is just add the version of the .NET SDK I need to the path.

However here is an issue, having it on SDK version updates on my repository to delete the old SDK version, and replace it with the new so then it gets removed from the cache.

**Comment by brianrob** [comment]
I'm not sure I follow.  Right now, when `setup-dotnet` runs, it still does an install - just to the %userprofile% directory, which means that its on the OS drive and subject to more aggressive throttling.

@rsemonov, @StanleyGoldman any thoughts on this?

**Comment by vsafonkin** [comment]
Hi @wasabii, you can try to set `DOTNET_INSTALL_DIR` environment variable to point a directory for .NET installation.

**Comment by IvanZosimov** [comment]
Hi, @brianrob 👋 I'm going to close this issue as it can be solved using `DOTNET_INSTALL_DIR` environment variable. If you have any additional questions, feel free to ping us.
