### ISSUE TITLE
SDK version 3.1.200 is always used

### ISSUE THREAD

**Issue by brunosantosrhsenso** [actions/setup-dotnet#153]
I have tried using both:

    - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

and

    - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.404

but 3.1.200 is always used:

C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_actions\actions\setup-dotnet\v1\externals\install-dotnet.ps1' -Version 3.1.200"

**Comment by vsafonkin** [comment]
Hello @brunosantosrhsenso , I've tested this and setup task is worked correctly. Do you still have any issues with it?
