### ISSUE TITLE
dotnet restore failed after they have upgraded .Net version to 5.0.

### ISSUE THREAD

**Issue by MohdmM01** [actions/setup-dotnet#154]
### Description

My github action failed because of dotnet restore issue for some of the packages. It is running on a Windows runner and was working yesterday but failed today. I suspect this is because of the recent change to .Net 5.0.

### Details

Failing dependencies:

D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.Services\JM.Formox.Services.csproj : error NU1101: Unable to find package Azure.Messaging.EventHubs.Processor. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.MicroService.sln]
D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.Services\JM.Formox.Services.csproj : error NU1101: Unable to find package Microsoft.Extensions.Http. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.MicroService.sln]
D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.Services\JM.Formox.Services.csproj : error NU1101: Unable to find package Microsoft.IdentityModel.Clients.ActiveDirectory. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\Formox---MicroService\Formox---MicroService\JM.Formox.MicroService.sln]

Github action setup for the project up to the restore section:

jobs:
build:

runs-on: windows-latest

steps:
- uses: actions/checkout@v2
- name: Setup .NET Core
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 3.1.100
- name: Install dependencies
  run: dotnet restore

**Comment by MohdmM01** [comment]
It is working after a while. Though current github status mentioned that only macos runner should be affected by the actions maintenance it affects Windows runner as well.

**Comment by tonykaralis** [comment]
Did you do anything to change it? I haven't run a pipeline in 18 days and now they fail.

**Comment by MohdmM01** [comment]
> Did you do anything to change it? I haven't run a pipeline in 18 days and now they fail.

You just have to add this in your workflow before dotnet restore:

    - name: Clean
      run: dotnet clean ./JM.Formox.MicroService.sln --configuration Debug && dotnet nuget locals all --clear
