### ISSUE TITLE
NuGet not restoring packages on runner.

### ISSUE THREAD

**Issue by chyyran** [actions/setup-dotnet#169]
**Description:**
`dotnet restore` does not restore packages and fails on Windows.

See https://github.com/SnowflakePowered/vcdiff/runs/1881693552

**Task version:**
1
**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
* Install .NET 5
* `dotnet restore`
https://github.com/SnowflakePowered/vcdiff/blob/master/.github/workflows/dotnet.yml

**Expected behavior:**
* Nuget restores packages from nuget.org

**Actual behavior:**

Restore fails because nuget can't find package IDs.

```
error NU1102: Unable to find package Microsoft.NET.Test.Sdk with version (>= 16.8.3) 
error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 16.6.1 ] 
error NU1101: Unable to find package xunit. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages 
...
```

**Comment by maxim-lobanov** [comment]
Duplicate: https://github.com/actions/setup-dotnet/issues/155
