### ISSUE TITLE
No Check Annotation for compile error in C# project

### ISSUE THREAD

**Issue by rainersigwald** [actions/setup-dotnet#17]
I [introduced a simple compile error](https://github.com/rainersigwald/bumblebee/pull/6/commits/10122ffed905bc0408ecb1894380402e53c2b7b4), which seems to have been matched by the problem matcher (it turned red in the console output view and is prefixed with `##[error]`), but there was no annotation linking the error to the file/line number information that is contained in the line.

https://github.com/rainersigwald/bumblebee/pull/6/checks?check_run_id=192916618#step:4:32

I hoped for the sort of linking in the Files Changed tab of the PR that are described in [the Checks CI docs](https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#step-25-updating-the-check-run-with-ci-test-results).

This _might_ be because the error includes only a relative-to-the-project filename, rather than relative-to-the-repo-root?

**Comment by rainersigwald** [comment]
Configuring the compiler to emit absolute paths as [here](https://github.com/rainersigwald/bumblebee/pull/6/checks?check_run_id=193435716#step:4:32) did _not_ resolve the problem.

**Comment by damccorm** [comment]
@ericsciple could you take a look? It looks to me like the regex _should_ match this so I'm not totally sure why we're seeing this behavior.

**Comment by ericsciple** [comment]
@rainersigwald sorry i didnt see this issue before now.

The relative path not lining up makes sense. The runner attempts to root relative paths to the repo root, and if that path doesnt exist then the file property gets dropped.

iirc the runner sets an environment variable `github=true`, so defaulting to absolute when that is set, might be something to consider.

However, I am surprised that emitting absolute paths did not resolve the problem. As long as the path is under the repo root, that should work. Thanks for the links, i'll fork your repro and play around with it.

**Comment by ericsciple** [comment]
@ZEisinger looking at the matcher for v1, it looks like it should look something more like this:

```
"pattern": [
  {
    "regexp": "^\\s*([^:]+)\\((\\d+),(\\d+)\\): (error|warning) ([^:]+): (.*) \\[(.+)\\]$",
    "file": 1,
    "line": 2,
    "column": 3,
    "severity": 4,
    "code": 5,
    "message": 6,
    "fromPath": 7
  }
]
```


frompath will root the relative file

also i noticed location isnt a thing, so line/column instead

**Comment by ericsciple** [comment]
...although the annotation still didnt come out correct... debugging the runner now

**Comment by ericsciple** [comment]
@ZEisinger I opened a pr to fix `fromPath` in the runner. There is a bug in the runner where it currently does not trim the file name (csproj) before rooting the `file`. I'll sync w/ folks tomorrow to get a better idea when we can roll the fix out to prod.

You may not want to update the matcher configuration to include `fromPath`, until the runner fix is deployed.

**Comment by ericsciple** [comment]
The agent has rolled out everywhere now and the `fromPath` field can be used. Sorry for the delay we had a freeze for a while and was waiting for agent to roll out.

**Comment by ericsciple** [comment]
@ZEisinger i'm unable to assign a different assignee. The runner changes are in now.

**Comment by StanleyGoldman** [comment]
I tested against this regex: https://regex101.com/r/MkisH3/4

**Comment by rainersigwald** [comment]
@StanleyGoldman Thanks! I updated my test PR to use the latest master and everything looks good with and without configuring MSBuild to emit absolute paths.
