### ISSUE TITLE
Using default action.yml results in error No usable version of the libssl was found

### ISSUE THREAD

**Issue by kizaonline** [actions/setup-dotnet#176]
**Description:**
 Im trying to use the default template suggested at https://docs.github.com/en/actions/guides/building-and-testing-net but am receiving an error when dotnet restore is run that no usable version of the libssl was found

**Task version:**
Latest as per https://docs.github.com/en/actions/guides/building-and-testing-net

**Platform:**
- [1] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [1] Hosted
- [ ] Self-hosted

**Repro steps:**  
1. Create action.yml in .github/workflowsdirectory with content
`
name: dotnet build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '2.2.103', '3.0', '3.1.x', '5.0.x']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
`
2. Push a commit to repro

**Expected behavior:**
Action checks to complete successfully

**Actual behavior:**
dotnet restore fails for first check(dotnet version 2.2.103) with error
`
dotnet restore
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_ROOT: /home/runner/.dotnet
No usable version of the libssl was found
/home/runner/work/_temp/74f1720d-c0a1-436b-8f97-7b4d6b94cf73.sh: line 1:  1736 Aborted                 (core dumped) dotnet restore
Error: Process completed with exit code 134.
`

**Comment by GGG-KILLER** [comment]
.NET 2.2 has been deprecated and is no longer supported. This might be the reason why.

**Comment by kizaonline** [comment]
Thanks @GGG-KILLER, removing 2.2 resolved the issue.

You are probably right about this not being the right place, but unfortunately https://docs.github.com/en/actions/guides/building-and-testing-net links to Githubs generic support which is a bit of a dead end for such a specific issue

**Comment by GGG-KILLER** [comment]
> Thanks @GGG-KILLER, removing 2.2 resolved the issue.
> 
> You are probably right about this not being the right place, but unfortunately https://docs.github.com/en/actions/guides/building-and-testing-net links to Githubs generic support which is a bit of a dead end for such a specific issue

Actually, they store their docs in a repository, so you can open a PR to fix it: https://github.com/github/docs/edit/main/content/actions/guides/building-and-testing-net.md

**Comment by GGG-KILLER** [comment]
The README on this repository needs to be edited as well to remove 2.2 from it.

**Comment by vsafonkin** [comment]
@GGG-KILLER, thank you! Closed as resolved, needs to improve docs.

**Comment by lanwin** [comment]
Does this Problem also now also exists with NET5? 

I have this exact problem now with "dotnet-version: 5.x.x"

**Comment by GGG-KILLER** [comment]
> Does this Problem also now also exists with NET5?
> 
> I have this exact problem now with "dotnet-version: 5.x.x"

Yes @lanwin, according to Microsoft's support policy .NET 5 is no longer supported as of May 10th:
![image](https://user-images.githubusercontent.com/5892127/212344953-ac169065-ce7e-4858-8d98-504b1e99480e.png)

**Comment by lanwin** [comment]
Well is there any way I can make the action run the builds again? 

I know the version is out of support. But I can not switch the dotnet version of that project right now. And every time someone checks in something into that repo, we get a failing build.

**Comment by GGG-KILLER** [comment]
> Well is there any way I can make the action run the builds again?

Can't help with that since I haven't had to fix this specific problem myself.
The only solutions I've seen being applied is upgrading to a newer .NET version, but maybe someone else can offer an alternative solution.
