### ISSUE TITLE
Support all three nuget.config name formats for greater cross platform consistency

### ISSUE THREAD

**Issue by xt0rted** [actions/setup-dotnet#181]
**Description:**

NuGet supports [`nuget.config`, `NuGet.config`, and `NuGet.Config`](https://github.com/NuGet/NuGet.Client/blob/2069de37565548a70b4313eea188fb1ced75bc40/src/NuGet.Core/NuGet.Configuration/Settings/Settings.cs#L24-L37) for the casing of the config file. This action [only supports `nuget.config`](https://github.com/actions/setup-dotnet/blob/77a48bbb85cd3809790223e895ba4b6cbc110fe8/src/authutil.ts#L16) which gives unexpected results when setting up package feeds, and when sharing workflows across OSes. A note should also be included in the readme mentioning the config file names supported since they matter.

**Justification:**

If you use `NuGet.config` and build on Ubuntu, depending on the sources in it, you end up getting a number of different build errors because the source wasn't found, it can't be since `nuget.config` doesn't exist. This leads to very confusing errors about packages not being found in feeds they don't belong to and/or GPR requests not being authenticated.

Even though `nuget.config` is the current preferred format (`dotnet new nugetconfig` uses it now for cross platform consistency), all three are officially supported by the nuget client and have been the preferred format at various points in time.

1. None of the [dotnet/*](https://github.com/search?q=user%3Adotnet+path%3A%2F+filename%3Anuget.config&type=Code&ref=advsearch&l=&l=) repos use the lowercase version.
2. A [general search](https://github.com/search?q=path%3A%2F+filename%3Anuget.config&type=Code&ref=advsearch&l=&l=) shows how common it is to not use the lowercase version.
3. Even https://github.com/actions/runner/blob/main/src/NuGet.Config isn't lowercase.
4. The nuget docs use all three formats, leading you to think the casing isn't important, which is confirmed when you restore/build successfully.
    - https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file
    - https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior
5. The format doesn't seem to matter for Dependabot in my testing.

**Are you willing to submit a PR?**

**Comment by vsafonkin** [comment]
Hi @xt0rted, could you please provide some minimal build with errors as repro?

**Comment by xt0rted** [comment]
I'm busy the rest of the week but I'll try to get a repro setup over the weekend for this.

**Comment by xt0rted** [comment]
@vsafonkin I created [3 PRs](https://github.com/xt0rted-test/actions-nuget-restore/pulls) showing how the different file name casing is handled on each OS. I didn't realize the macOS vms were all set to be case insensitive which means that currently only Ubuntu doesn't work as expected but it could become a larger issue as more runners are introduced.

**Comment by xt0rted** [comment]
I'm not seeing any way to do a case insensitive check with the node apis, but something like this should work unless you wan to check for the 3 common casings only.

```diff
diff --git a/src/authutil.ts b/src/authutil.ts
index 463f0d3..fe91b77 100644
--- a/src/authutil.ts
+++ b/src/authutil.ts
@@ -1,20 +1,37 @@
 import * as fs from 'fs';
 import * as path from 'path';
+import { promisify } from 'util';
 import * as core from '@actions/core';
 import * as github from '@actions/github';
 import * as xmlbuilder from 'xmlbuilder';
 import * as xmlParser from 'fast-xml-parser';
-import {ProcessEnvOptions} from 'child_process';

+const readdirAsync = promisify(fs.readdir);
+
+async function getExistingConfig(
+  existingFileLocation: string,
+  processRoot: string,
+): Promise<string> {
+  if (existingFileLocation != '') {
+    return path.resolve(processRoot, existingFileLocation);
+  }
+
+  const files = await readdirAsync(processRoot);
+  for (const file in files) {
+    if (path.basename(file).toLowerCase() === 'nuget.config') {
+      return file;
+    }
+  }
+
+  return path.resolve(processRoot, 'nuget.config');
+}
+
-export function configAuthentication(
+export async function configAuthentication(
   feedUrl: string,
   existingFileLocation: string = '',
   processRoot: string = process.cwd()
 ) {
-  const existingNuGetConfig: string = path.resolve(
-    processRoot,
-    existingFileLocation == '' ? 'nuget.config' : existingFileLocation
-  );
+  const existingNuGetConfig: string = await getExistingConfig(existingFileLocation, processRoot);

   const tempNuGetConfig: string = path.resolve(
     processRoot,
```

**Comment by vsafonkin** [comment]
@xt0rted, thank you for the details!

**Comment by vsafonkin** [comment]
comment: https://github.com/actions/setup-dotnet/issues/182#issuecomment-825523465
