### ISSUE TITLE
Better package source name validation

### ISSUE THREAD

**Issue by xt0rted** [actions/setup-dotnet#182]
**Description:**

Authenticated package feeds can only use `a-z`, `0-9`, `-`, `_`, and `.` in their name because the name gets used as the element name for the credentials. Currently this action [only checks for spaces](https://github.com/actions/setup-dotnet/blob/77a48bbb85cd3809790223e895ba4b6cbc110fe8/src/authutil.ts#L112-L116) but xml has a number of limitations that can catch you off guard here.

**Justification:**

You can name your sources just about anything and if you use a format like `github.com/ORG` you're fine right until you try to let the action setup the credentials for you. Having a better name check would help prevent unneeded debugging due to a seemingly ok config that really isn't.

**Are you willing to submit a PR?**

**Comment by vsafonkin** [comment]
Hi @xt0rted, could you please clarify the issues you faced? I've tried to publish package to organization with `VSORG-1` name and it works correctly:
action run: https://github.com/VSORG-1/dotnet-setup-test/actions/runs/721831947
package: https://github.com/orgs/VSORG-1/packages

**Comment by xt0rted** [comment]
The issue is with the package source name, not the org name. Mine was set to `github.com/xt0rted` so when this action tried to set the auth token it failed because that name is used as the name of an xml element and `/` is an invalid character.

https://github.com/actions/setup-dotnet/blob/51f68377c181a79065c61bd492bd49be4575c439/src/authutil.ts#L112-L120

The build log ends up having a fairly unhelpful error when this happens.

![github com_xt0rted_plant-directory_runs_2257963175_check_suite_focus=true](https://user-images.githubusercontent.com/831974/113939398-f33cc980-97c9-11eb-8719-0ef80bb83b6a.png)

The check is only looking for spaces but there's more invalid characters/formats than that. When I switched my package source name to `github-xt0rted` the issue went away.

![github com_xt0rted_plant-directory_pull_46_files](https://user-images.githubusercontent.com/831974/113939214-b1ac1e80-97c9-11eb-9f89-bd722539af9d.png)

**Comment by vsafonkin** [comment]
Hi @xt0rted, PRs for your suggestions were merged and new release for task will be created on next week, thank you for your help!
