### ISSUE TITLE
Empty NuGet.config file causing restore failures with 5.0.202

### ISSUE THREAD

**Issue by marcpopMSFT** [actions/setup-dotnet#184]
**Description:**
I was told this might be the right repo for filing this issue. Also sent email to a few contacts at GH.

We're seeing customer reports of customers using GitHub Actions with 5.0.202 and failing to restore any files from Nuget.org.  This appears to be because the machine has an empty nuget.config file picked up by the build process which causes NuGet to ignore nuget.org.

Example customer reports along with workaround
https://github.com/dotnet/installer/issues/10171

NuGet change that affected this
https://github.com/NuGet/NuGet.Client/pull/3907

**Task version:**
Unknown

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
name: .NET
on:
push:
branches: [ master ]
pull_request:
branches: [ master ]
jobs:
build:
runs-on: windows-latest
steps:
- uses: actions/checkout@v2
- name: Setup .NET
uses: actions/setup-dotnet@v1
with:
dotnet-version: 5.0.x
- name: Restore dependencies
run: dotnet restore
- name: Build
run: dotnet build --no-restore
- name: Test
run: dotnet test --no-build --verbosity normal

**Expected behavior:**
Build succeeds restoring files from NuGet.org.
https://github.com/pownas/asp-net-yaml-yml-build-tester/runs/2283517744?check_suite_focus=true

**Actual behavior:**
 error NU1101: Unable to find package Microsoft.AspNetCore.Identity.UI. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
https://github.com/pownas/asp-net-yaml-yml-build-tester/runs/2283517744?check_suite_focus=true

**Comment by marcpopMSFT** [comment]
Sample repro from Andy.  Looks like Maxim is engaged in email now.
https://github.com/zivkan/ci-nugetconfig-check/runs/2292176156?check_suite_focus=true

**Comment by maxim-lobanov** [comment]
Related issue: https://github.com/actions/virtual-environments/issues/3038

**Comment by samsmithnz** [comment]
I'm hitting this too. Short term workaround seems to be to use .NET 5.0.201:

```
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
```

**Comment by vsafonkin** [comment]
PR with fix for Windows runner was merged: https://github.com/actions/virtual-environments/pull/3144

**Comment by vsafonkin** [comment]
Related issue in choco repository: https://github.com/chocolatey/choco/issues/2233

**Comment by vsafonkin** [comment]
Hi @marcpopMSFT, do you still have this issue?

**Comment by marcpopMSFT** [comment]
From internal emails, I believe this has been resolved in GH actions at this point.
