### ISSUE TITLE
Error parsing `global.json` with encoding `utf8 with BOM`

### ISSUE THREAD

**Issue by petarpetrovt** [actions/setup-dotnet#185]
**Description:**
Parsing of the `global.json` fail if its saved with BOM.
Node.js dosen't strip BOM. - [issue](https://github.com/nodejs/node/issues/20649)
Trimming the string should fix the issue.

**Task version:**
1.7.2

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Expected behavior:**
Parse `global.json` correctly.

**Actual behavior:**
Throws `Error: Unexpected token ﻿ in JSON at position 0`

**Comment by vsafonkin** [comment]
Hi @petarpetrovt, thank you for your report! We will investigate it.

**Comment by vsafonkin** [comment]
New task version with fix was released, tag `v1.8.0` or `v1`. Thank you for your help!
