### ISSUE TITLE
Add configuration option so action can run ``dotnet restore`` for us.

### ISSUE THREAD

**Issue by AraHaan** [actions/setup-dotnet#199]
**Description:**
Currently we all have to have shell, powershell, bash, or even use command prompt in github actions in order to run ``dotnet restore`` before build + test + pack. I usually run ``dotnet restore`` first so that way it speeds up the CI and sometimes I cache the restored output to speed up future CI's and update it if the cache is outdated due to something like an updated dependency.

**Justification:**
This use case of this is so then users like me who do this as part of speeding up the CI could use the action to execute this command and so that way it makes their workflows smaller, more readable and maintainable.

**Are you willing to submit a PR?**

If possible, yes.

**Comment by vsafonkin** [comment]
Hi @AraHaan, thank you for your proposal. In my opinion, restoring of nuget packages is not in the scope of `setup-dotnet` task functionality and `restore` operation will be better to execute explicitly  as separated step.

**Comment by AraHaan** [comment]
@vsafonkin happen to know if it's possible to embed this action (``setup-dotnet``) inside of another action I wrote (use it from my action's index.js file)?

**Comment by vsafonkin** [comment]
@AraHaan https://github.com/actions/setup-dotnet/issues/206#issuecomment-864096990

**Comment by AraHaan** [comment]
> @AraHaan [#206 (comment)](https://github.com/actions/setup-dotnet/issues/206#issuecomment-864096990)

Why was this closed when this issue technically was not about #206 (despite me commenting a question about it here).

**Comment by IvanZosimov** [comment]
Hi, @AraHaan 👋 We closed this issue because of the comment above https://github.com/actions/setup-dotnet/issues/199#issuecomment-847841665 . Meantime, as you said about speeding up your workflow with `dotnet restore` command, could you also provide us with info about your time improvements (like workflow execution time with/without using `dotnet restore`)?

**Comment by AraHaan** [comment]
Sure, on some of my projects (ones with over 14 of them in the solution file) not adding restore first (about 14 seconds with restore) can result in build time increases by about a minute or so (which can be major when it comes to sometimes getting close to build timeouts when running extensive tests after the build in specific testing steps in a job I could separate the tests into an separate job but it would then list an extra status check that I do not have configured in my mergify rules either). Yes I have some rules where pull requests created from some github bots (dependabot for example) get automatically merged when all checks pass.

**Comment by IvanZosimov** [comment]
Thanks for the answer, @AraHaan !  I tested your theory on a small solution with only 3 projects and for such a small solution I saw no time improvements at all 😿  Nonetheless, I can agree with my colleague @vsafonkin that restoring functionality is not in the scope of `setup-dotnet` and even if it's added to `setup-dotnet`, it wouldn't add any performance boost in contrast to `dotnet restore` + `dotnet build` as an additional step.

**Comment by Mohsen8136** [comment]
به نام حق که بخشنده و مهربان هست جزو اصلیترین صفتهایش در ۱۱۳ سوره   ابتدا
دعا کنید بی ریا و از حضرت حق آرزوی توفیق در گرامی داشت این بانوی عزیز و
عزیزانش که عزیزان شما محسوب میشوند. قدم اول وظیفه دادستان کشور این هست و
باید باشد که فردی که تهدید کرده این عزیز را و مسبب اصلی هست را در برابر
دوربین و با صورت کاملا مشخص توضیح دهد که آیا آموزش دیده بوده یا نه..واز کار
تعلیق و پرونده را کاملا روشن و بهتر حرکت دهید..هر کس شغلش قدم دوم همگان
دعوت به آرامش و گلهای زیاد از هوا و زمین بر شهرها فرود آید و گرازهای
خیابانی جمع شوند و خادمین مردم در لباس عادی و شال سیاه در شغل خود حاضر شده
و سر را پایین نگه دارند و آماده کتک خوردن هم باشند بدون پاسخ ..دستور ۳م۹
ثبت پخش اجرا  بسازید خراب نکنید  آباد کنید ویران نکنید ستم نکنید شما از چه
سفره نان خردید از کدام اصول برخورداری؟کدام خدا را قبول داری؟لعنت و نفرین
نکن دعا کن بساز گراز رو تبدیل به ماهی کن دعوا نکن دعوت کن شعار نده شعر بگو

در تاریخ جمعه ۲۶ اوت ۲۰۲۲،‏ ۱۴:۰۷ AraHaan ***@***.***> نوشت:
