### ISSUE TITLE
Use recommended release strategy

### ISSUE THREAD

**Issue by damccorm** [actions/setup-dotnet#20]
We should be using the release strategy specified by https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations

To get there, we need to:
1) Create a `releases/v1` branch and move the `v1` tag and future releases there
2) Warn that we will deprecate the master branch and that you should attach to `v1` instead. We will support master in a warned but deprecated state for ~1 month.
3) Switch the warning to an error on master. Remove `node_modules` from the master branch. We will stay in this state for ~1 month.
4) Remove the error on master.

During steps 2 and 3, we need to be extra careful to not check the warning/error into the releases branch.

**Comment by ZEisinger** [comment]
@stbeam Step 1 is completed and we can continue to step 2

**Comment by ZEisinger** [comment]
Step 2 is now completed. Step 3 will be addressed in late November.

**Comment by bryanmacfarlane** [comment]
We're not doing this.  Instead, we're moving toward ncc and packing.  Will open a separate issue.  See the javascript-action repo for an example

**Comment by ZEisinger** [comment]
Original changes have been removed. Will need to implement the new recommended strategy for packaging: https://github.com/actions/javascript-action#package-for-distribution

**Comment by ZEisinger** [comment]
This was completed a while back and has been working well
