### ISSUE TITLE
Could not download .NET Core 3.1

### ISSUE THREAD

**Issue by i2van** [actions/setup-dotnet#205]
**Description:**
Could not download .NET Core 3.1. [Workflow file](https://github.com/i2van/CsvLINQPadDriver/blob/42cdcb4c6aeb5fa65e82250c66aac50717a300bd/.github/workflows/build.yml)

**Task version:**
actions/setup-dotnet@v1

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Run [workflow](https://github.com/i2van/CsvLINQPadDriver/blob/42cdcb4c6aeb5fa65e82250c66aac50717a300bd/.github/workflows/build.yml).

**Expected behavior:**
Should build. Worked before, see [history](https://github.com/i2van/CsvLINQPadDriver/actions).

**Actual behavior:**
```
Run actions/setup-dotnet@v1
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_actions\actions\setup-dotnet\v1\externals\install-dotnet.ps1' -Version 3.1.0"
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.0/dotnet-sdk-3.1.0-win-x64.zip
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.0/dotnet-sdk-3.1.0-win-x64.zip is not available.
dotnet-install: Downloading legacy link https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.0/dotnet-dev-win-x64.3.1.0.zip
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.0/dotnet-dev-win-x64.3.1.0.zip is not available.
Could not find ".NET Core SDK" with version = 3.1.0
```

**Comment by i2van** [comment]
Adding exact SDK version to [global.json](https://github.com/i2van/CsvLINQPadDriver/blob/master/global.json) fixed this issue but also failed the build.

**Comment by vsafonkin** [comment]
Hi @i2van, you're right, setup task ignores `rollForward` property in `global.json`. But `global.json` is ignored if you specify version in your workflow file as in example above. If you use `global.json` you should specify exact version.
