### ISSUE TITLE
Allow using action within another action.

### ISSUE THREAD

**Issue by AraHaan** [actions/setup-dotnet#206]
**Description:**
I would like to be able to invoke the code that this action does within my own github action. I plan on doing this so that way it will install, restore, build, test, and pack my .NET Code all in a single step.

**Justification:**
My justification is so that way I can make my workflows as small as possible while also being able to do what is needed.

**Are you willing to submit a PR?**

Maybe?

Note: Not sure what would be needed to be done to make it work. Would the action need an npm version and as such go into ``node_modules``?

**Comment by vsafonkin** [comment]
Hi @AraHaan, unfortunately, there is no possible to get this action as npm package in order to use it in js code at the moment. Maybe it wiil be possible in future. Thanks!

**Comment by Boocakes** [comment]
No

**Comment by AraHaan** [comment]
@vsafonkin so what did you guys decide on this? I would still love to be able to consume the code this action uses as a ``node_module`` to my own github action so that way it can help optionally make people's workflow files smaller.

**Comment by vsafonkin** [comment]
@AraHaan, we do not plan to publish the code of this action as npm package in the near future, sorry.
