### ISSUE TITLE
Guide for beginners

### ISSUE THREAD

**Issue by EgoPingvina** [actions/setup-dotnet#207]
**Description:**
Is there a guide somewhere for beginners how to use this?

**Justification:**
Write please a step-by-step guide on what to do to deploy your ASP.Net Core (3.1 for example) project

**Comment by vsafonkin** [comment]
Hi @EgoPingvina, the setup action installs the required version of .NET, the possibilities of the .NET are described in the Microsoft documentation: [link](https://docs.microsoft.com/en-us/dotnet/core/tools/). The application deployment process will be different for different environments: Azure, AWS and etc. I believe there is no need to describe it in setup action repository. Thanks!

**Comment by timheuer** [comment]
@EgoPingvina here's a sample usage for a full project including deploying to Azure: https://github.com/timheuer/aspnet-core-sample-deploy/blob/master/.github/workflows/build-and-deploy.yml
