### ISSUE TITLE
Support installing from daily aka.ms feeds.

### ISSUE THREAD

**Issue by AraHaan** [actions/setup-dotnet#219]
**Description:**
It should be possible to have setup-dotnet download and install the .NET SDKs from:
- https://aka.ms/dotnet/6.0/daily/
- https://aka.ms/dotnet/6.0/preview/

Each of them also contain a text file for each platform and CPU bitness that the installers are available in and it contains the versions of those installers:
- ``productCommit-win-x64.txt`` for 64 bit Windows.
- ``productCommit-linux-x64.txt`` for 64 bit linux.
- ``productCommit-osx-x64.txt`` for 64 bit MacOS.

The installer files (SDKs and not the runtimes):
- ``dotnet-sdk-win-x64.exe``
- ``dotnet-sdk-linux-x64.tar.gz``
- ``dotnet-sdk-osx-x64.pkg``

**Justification:**
I need this and the ability to tell the action ``use the preview feed`` which is the one this action currently uses or the ``use the daily feed`` which is the feed that contains the Preview 7 versions, the rc.1 versions of .NET 6, etc which my codebase needs that Preview 6 lacks.

**Are you willing to submit a PR?**

If the change is not too hard to make that is.

**Comment by vsafonkin** [comment]
Hi @AraHaan, could you please clarify, what feeds do you mean? The short links redirect me to Bing.

You can use `include-prerelease` option to install dotnet 6.0 preview:
```
uses: actions/setup-dotnet@v1
with:
   dotnet-version: '6.0'
   include-prerelease: 'true'
```
As I see, the latest version is `6.0.100-preview.6.21355.2`.

**Comment by AraHaan** [comment]
Yes, while the ones on the link to ``aka.ms/dotnet/daily/`` point to ``6.0.100-rc.1`` as the latest, Also those links redirected to bing as you would have to paste in the file names I posted in separate \`\`text\`\` blocks.

**Comment by AraHaan** [comment]
Welp it looks like the action could do this if it could nuke the version lookup and explicitly passing the version into the dotnet install script. So if there was an option to disable that, an option to set the quality which then gets passed to the script, with the major.minor strings passed in based on what the input version string is (if it's just a version with a single dot like for example '6.0' then the script would look in the daily feed and then install the rc.1 build of the 6.0.100 .NET SDK.

**Comment by vsafonkin** [comment]
@AraHaan, thank for your help, as I see, it could be implemented with the option `quality` for installer scripts, for example:
```./dotnet-install.sh --channel '6.0' --quality 'daily'
or
./dotnet-install.ps1 -Channel '6.0' -Quality 'daily'
```
Unfortunately, the current action implementation uses only `version` option for installer scripts. We are planning rework the action in the near future to use `channel` option, and probably `quality` input will be added.
At the moment you can install these versions only specifying exact version, for example:
```
uses: actions/setup-dotnet@v1
with:
    dotnet-version: '6.0.100-rc.1.21372.2'
```

**Comment by AraHaan** [comment]
Instead I deployed my own action ``Elskom/setup-latest-dotnet`` and pinned it to ``@main``.

**Comment by IvanZosimov** [comment]
Hi, @AraHaan  👋  The functionality you asked for was implemented in the new [`v3`](https://github.com/actions/setup-dotnet/tree/v3) version of `setup-dotnet` action. By now I'm going to close this issue, If you have any additions or questions feel free to ping us.
