### ISSUE TITLE
Set DOTNET_CLI_TELEMETRY_OPTOUT=1

### ISSUE THREAD

**Issue by xPaw** [actions/setup-dotnet#22]
> Telemetry
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

> Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

I don't think it's needed for CI runs. Travis sets this by default: https://github.com/travis-ci/travis-build/pull/1191/files

**Comment by khellang** [comment]
Does it make sense to also set `DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1`?

**Comment by damccorm** [comment]
My instinct is to leave the telemetry on by default - I think if we can be helpful and provide telemetry back to .NET I'd probably rather do that by default and support them so that they can use that to make the product better!

I think I'm actually also hesitant to set `DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1` - my reasoning here is that while this definitely makes sense for hosted pools, it seems like we wouldn't want this for private runners.

I'm not 100% sure on either of these, but that's my initial instinct - thoughts?

**Comment by Kissaki** [comment]
> to leave the telemetry on by default - I think if we can be helpful and provide telemetry back to .NET I'd probably rather do that by default and support them so that they can use that to make the product better!

I agree. A bit of log output like that is not really a hindrance for users.

The collected and transmitted data is undeniably not a security concern, but will help upstream quite a bit. It is the default behavior of the dotnet environment, and there should be a compelling reason to change that default.

If users want to prevent it they can set the environment variable themselves. It’s not like this action prevents them from disabling it. This is merely about the default, and I think transmission is totally fine.

---

To elaborate a bit more; let me explore two use cases.

A public repository will not have problems disclosing some build information, and submitting some generic statistics to dotnet upstream.

A private repository may be more conservative and restrictive, but as I said they can still set the environment variable to disable it themselves.

**Comment by ZEisinger** [comment]
It seems we are agreed on leaving telemetry on. But I like the log message dotnet adds and think it would be useful.

For DOTNET_SKIP_FIRST_TIME_EXPERIENCE, my testing was not showing any improvement. Looking though some dotnet stuff I see that 3.0 may no longer do the dotnet priming that was causing slowness on the first run: https://github.com/dotnet/cli/issues/4919#issuecomment-488060488

Personally I think adding descriptions of a couple relevant environment variables to the README would provide value without setting up an environment that is not the default. This could also cover #10.

**Comment by gitfool** [comment]
Please make this configurable via action parameters; this should only be a debate about the default values. It would be really nice to conveniently disable telemetry and first time experience as part of installing dotnet via this action.

Note: the way to disable first time experience seems to have changed in dotnet core 3.0 and now uses a [sentinel file](https://github.com/dotnet/sdk/issues/3828#issuecomment-557768792). Yet another reason to make such an option a parameter to this action.

**Comment by ZEisinger** [comment]
Closing this issue, the improved documentation provides ways to disable the first run message and telemetry.
