### ISSUE TITLE
When using global.json value of rollForward should be considered

### ISSUE THREAD

**Issue by henrikrxn** [actions/setup-dotnet#223]
Have not set the dotnet sdk version in the workflow and have the following global.json in my project

```json
{
  "sdk": {
    "version": "3.1.410",
    "allowPrerelease": false,
    "rollForward": "latestFeature"
  }
}
```

At the time I am writing this there is both 3.1.411 and 3.1.412 available, but the action always uses 3.1.410

Would like the action to either use the value specified in "rollforward" by default or be able to configure the action to use the value.

Justification: Do not want to have to maintain the SDK version in two places

**Comment by vsafonkin** [comment]
Hi @henrikrxn, `global.json` is ignored if you specify version in action:
```
 - name: Setup dotnet
   uses: actions/setup-dotnet@v1
   with:
     dotnet-version: '3.1'
```
or if you don't specify version in action but only in `global.json`, you can use `X.Y` format to install the latest feature version, for example:
```
{
  "sdk": {
    "version": "3.1",
    "allowPrerelease": false,
    "rollForward": "latestFeature"
  }
}
```

**Comment by henrikrxn** [comment]
Thank you. Did not know you can use only major.minor, which is fine for me. Should have read the docs in more detail
https://docs.microsoft.com/en-us/dotnet/core/versions/selection#framework-dependent-apps-roll-forward

Feel free to close if you do not feel the feature is worth while implementing

**Comment by henrikrxn** [comment]
Did some more investigating and I do not think using only major.minor in global.json is a good idea.

When using "3.1" as version in global.json:

```json
{
  "sdk": {
    "version": "3.1",
    "allowPrerelease": false,
    "rollForward": "latestFeature"
  }
}
```

- Github actions pick up highest 3.1 version, i.e. in my example 3.1.412
- `dotnet --version` in a console picks up a different version. In my case it picks up the .NET 6 preview I have installed

When using "3.1.410" as version in global.json:

```json
{
  "sdk": {
    "version": "3.1.410",
    "allowPrerelease": false,
    "rollForward": "latestFeature"
  }
}
```

- Github actions pick up highest 3.1 version, i.e. in my example 3.1.412
- `dotnet --version` in a console picks up a different version. In my case it picks up the .NET 6 preview I have installed.

So I think the feature request has merit as it should result in a uniform resolution af SDK across "everything"

**Comment by vsafonkin** [comment]
@henrikrxn, you're right, it's my mistake. It works for `setup-dotnet` action because the action gets only version from `global.json` to install SDK and the action can handle major.minor input, but it not works correctly locally. Thank you for your help!

**Comment by henrikrxn** [comment]
No problem. Let's just agree that the versioning scheme for runtime vs. SDK vs. global.json is neither straight forward nor uniform

**Comment by adamralph** [comment]
This is done and released, no?

**Comment by vsafonkin** [comment]
@adamralph, yes, `v1` tag will be updated in 1 hour.

**Comment by vsafonkin** [comment]
@henrikrxn, support for `rollForward` as `latestFeature` has been added. I close this issue, please, feel free to reopen it if you have any concerns.

**Comment by henrikrxn** [comment]
Just updated my workflows + global.json and everything works as expected

Thx for the effort.

**Comment by delreluca** [comment]
Would it make sense to support `latestMinor` as well? I chose that option (with the current versioning scheme I guess the difference between minor and feature is one of style) and the action ignores it. In #339 someone wants support for `latestPatch` and there are a lot more options supported by the JSON file. If not all of them are supported by the action it should be noted in the README.

**Comment by rubo** [comment]
Why doesn't the action support other options for `rollForward` besides `latestFeature`? Is there any particular reason? I'd expect the action to behave as described in the [`rollForward` docs](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#rollforward).
