### ISSUE TITLE
Update to use releases-index.json instead of (obsolete) releases.json

### ISSUE THREAD

**Issue by natemcmaster** [actions/setup-dotnet#24]
The installer code is using an endpoint which is obsolete. https://github.com/actions/setup-dotnet/blob/56ad7c692775dd91f93f2dc92b2ec61101dde8a7/src/installer.ts#L349-L350

Supposedly, this is going to be deleted soon (cref https://github.com/dotnet/core/pull/3167, https://github.com/dotnet/core/pull/3168)

https://github.com/dotnet/announcements/issues/87 contains details on the new format, release-index.json.

cc @leecow

**Comment by damccorm** [comment]
Good call, thanks for pointing this out. Looks like it may be getting removed next week.
