### ISSUE TITLE
Add sample for netstandard 2.0

### ISSUE THREAD

**Issue by klacol** [actions/setup-dotnet#246]
**Description:**
Great effort here. It works fine.
I am in the process of migration a bigger app to .NET 6.0 (in the end). 

Meanwhile I have to compile some projects in "netstandard 2.0" to be able to still hold a reference to the .NET Framework 4.x projects.

Please add a sample, how to configure this situation, if it is supported by setup-dotnet

**Are you willing to submit a PR?**
I would, if I could :-)

**Comment by vsafonkin** [comment]
Hi @klacol, .NET Framework 4.8 is installed by default on the Windows runner, no need to use `setup-dotnet` task for it. This action installs .NET Core versions and doesn't support .NET Framework installation.

**Comment by klacol** [comment]
Ok, thanks, I always thought, I would need an .NET Core SDK to compile projects with `netstandard2.0`.  I will try it out.

**Comment by vsafonkin** [comment]
Closed, please contact us if you have any questions.
