### ISSUE TITLE
Missing release, README has features not yet published

### ISSUE THREAD

**Issue by LanceMcCarthy** [actions/setup-dotnet#249]
Hi Team,

The readme shows features that are not yet published, although they have been merged, (e.g., setting multiple .NET versions). Can someone please trigger a release workflow build so that we can get 1.9 published?

Thanks!

> Side note: I didn't want to use the `Bug` label, but didn't see a more general feedback option. Please change it to a more appropriate option if you think it should be there instead :)

**Comment by vsafonkin** [comment]
Hi @LanceMcCarthy, the new release of action will be published today, sorry for delay.

**Comment by LanceMcCarthy** [comment]
@vsafonkin Thank you!

**Comment by vsafonkin** [comment]
Tag `v1` was updated, closed.
