### ISSUE TITLE
Add a way to disable .NET Core 2.1 warning

### ISSUE THREAD

**Issue by KungA** [actions/setup-dotnet#251]
Our builds [are full of](https://github.com/vostok/metrics/actions/runs/1498415059) warnings:
```
.NET Core 2.1 is no longer supported and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the .NET support policy.
```

We are sure, that our libraries are should be compiled and run under `netstandard2.0`.

`<NoWarn>NETSDK1138</NoWarn>` disables this warning during the build, but how to disable it during `setup-dotnet`?

**Comment by zcsizmadia** [comment]
Most likely .NET Core 2.1 is used to build the project.  If yes, just use 3.1, 5.0 or 6.0

**Comment by codebude** [comment]
I just wanted to say, that I would be happy too, if you could add a switch/flag/parameter that allows disabling of EOL warnings.

**Comment by KungA** [comment]
> The setup-dotnet step itself should not be too many warnings. I assume only one.

One per each job (so up to 10-20 per workflow) :)

**Comment by mattjohnsonpint** [comment]
Workaround: If you supply the *exact* version, the warning does not appear.

Instead of `dotnet-version: 2.1.x`, use `dotnet-version: 2.1.818`

**Comment by IvanZosimov** [comment]
Hi, the issue was solved in the new `v3` version of `setup-dotnet` action.
By now I'm going to close this issue, If you have any additions or questions feel free to ping us.
