### ISSUE TITLE
6.0.200-preview.22055.15 is unavailable

### ISSUE THREAD

**Issue by HavenDV** [actions/setup-dotnet#268]
**Description:**
My log:
```
Run actions/setup-dotnet@v1
  with:
    dotnet-version: 6.0.x
    include-prerelease: true
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_actions\actions\setup-dotnet\v1\externals\install-dotnet.ps1' -Version 6.0.102"
```

It installs 6.0.102.

**Task version:**
v1

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
6.0.200-preview.22055.15 is available in the latest preview versions of VS 17.1

**Actual behavior:**
A description of what is actually happening.

**Comment by vsafonkin** [comment]
Hi @HavenDV, the action resolves version from this source: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json and the latest available SDK version in this source is 6.0.102 at the moment. You can install SDK 6.0.200 by specifying the exact version:
```yaml
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 6.0.200-preview.22055.15
```

**Comment by HavenDV** [comment]
Hello. Thanks for the quick response and suggested solution.
I think I'll wait for the .Net 7 preview, which should be out this week. I hope it will be present in this list and will not have to be specified explicitly.

**Comment by vsafonkin** [comment]
@HavenDV, .NET 7 preview is available and .NET SDK 6.0.200 is available as well.

**Comment by HavenDV** [comment]
Yes, I noticed, thank you for the notification
