### ISSUE TITLE
Yuu

### ISSUE THREAD

**Issue by inosgun** [actions/setup-dotnet#269]
**Description:**

**Task version:**
Specify the task version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.. ©4826919

**Comment by Peri112** [comment]
Open

Android için Outlook<https://aka.ms/AAb9ysg>’u edinin
________________________________
