### ISSUE TITLE
Problems with building .NET Framework 4.6.1 after overriding `v1` tag

### ISSUE THREAD

**Issue by dpraimeyuu** [actions/setup-dotnet#274]
**Description:**
Context: In our project we're using `setup-dotnet` to build .NET Framework 4.6.1 console applications.
1. Five days ago I made a PR and build was successful.
2. I made PR today and it failed - workflow yml definition hasn't changed - there was `actions/setup-dotnet@v1`.
3. I triggered `re-run` on previous PRs and they failed too (even though 5 days ago they got "green").
4. I checked the releases of `setup-dotnet` and saw new one - `v1.9.1`. What's more, I observed that `v1` was updated too?
![image](https://user-images.githubusercontent.com/6437191/155553996-73dd3b0d-c0bd-4f97-bfd0-75c6f57ce32b.png)

I checked that install scripts changed in the latest release and I wonder if that might be the cause of our jobs failing?

**Task version:**
`v1`

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
Without changing task version, existing build started failing.

**Actual behavior:**
Keeping the same version of task shouldn't introduce breaking changes

**Comment by dpraimeyuu** [comment]
Hi @vsafonkin ! Sorry for unclear message :-)

Yes, my workflow failed without any changes from our side.

> Could you please check .NET version in successful and failed builds?
Do you mean .NET version used in our solution and .NET version used by the task?
* all projects within solution `.NET Framework 4.6.1`
* `global.json` points to `2.1.403`
* using `actions/setup-dotnet@v1`
* version specified in workflow's manifest `2.1.403`

**Comment by dpraimeyuu** [comment]
> Run actions/setup-dotnet@v1
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_actions\actions\setup-dotnet\v1\externals\install-dotnet.ps1' -Version 2.1.403"

**Comment by vsafonkin** [comment]
And the failed build has the same version?

**Comment by vsafonkin** [comment]
Also could you check the Windows runner version in `set up job` step for failed and successful builds?
<img width="816" alt="Screenshot 2022-02-24 at 7 13 53 PM" src="https://user-images.githubusercontent.com/7628945/155563577-d8b2d88a-011a-495b-83f4-03784a48e543.png">

**Comment by dpraimeyuu** [comment]
![image](https://user-images.githubusercontent.com/6437191/155583975-5cc44124-248a-421d-a9c4-037bb8f37761.png)

**Comment by Peri112** [comment]
Hbxbfbahss

Android için Outlook<https://aka.ms/AAb9ysg>’u edinin
________________________________
