### ISSUE TITLE
SDK versions already on the VM are installed a second time and pre-installed SDKs become unavailable

### ISSUE THREAD

**Issue by xt0rted** [actions/setup-dotnet#284]
**Description:**

Calling this action with an SDK version pre-installed on the VM causes it to be installed a second time and the pre-installed SDKs become unavailable.

**Task version:** v2

**Platform:**

- [x] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**

- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

Call `actions/setup-dotnet` with a list of sdks that are pre-installed:

```yml
- name: Set up .NET
  uses: actions/setup-dotnet@v2.0.0
  with:
    dotnet-version: |
      3.1.417
      5.0.406
      6.0.201
```

**Expected behavior:**

1. For any SDK version installed by this action to be skipped if it's already installed on the VM.
2. All pre-installed SDKs to be available after calling this action.

**Actual behavior:**

On `macos-latest` the v3 and v5 SDKs are skipped because they're already installed while v6 is downloaded and installed. Calling this a second time shows all 3 SDKs being skipped. After calling this action the pre-installed and newly installed SDKs are shown with `dotnet --info`.

On `ubuntu-latest` and `windows-latest` all 3 SDKs are downloaded and installed even though they're pre-installed. Calling this a second time shows all 3 SDKs being skipped. After calling this action only the newly installed SDKs are shown with `dotnet --info`, any pre-installed SDK becomes unavailable.

This is being caused by the installation location of the SDKs on Ubuntu and Windows differing from the pre-installed location, while on macOS it's the same location.

Two test runs can be seen here:

- [Latest patch versions](https://github.com/xt0rted-test/setup-dotnet-test/actions/runs/2148868921)
- [Explicit versions](https://github.com/xt0rted-test/setup-dotnet-test/actions/runs/2148882365)

Calling `dotnet --info` gives the following results (see the above build logs for more info):

**macOS out of the box**

```
.NET SDKs installed:
  3.1.101 [/Users/runner/.dotnet/sdk]
  3.1.201 [/Users/runner/.dotnet/sdk]
  3.1.302 [/Users/runner/.dotnet/sdk]
  3.1.417 [/Users/runner/.dotnet/sdk]
  5.0.102 [/Users/runner/.dotnet/sdk]
  5.0.202 [/Users/runner/.dotnet/sdk]
  5.0.302 [/Users/runner/.dotnet/sdk]
  5.0.406 [/Users/runner/.dotnet/sdk]
```

**macOS after calling `actions/setup-dotnet`**

```
.NET SDKs installed:
  3.1.101 [/Users/runner/.dotnet/sdk]
  3.1.201 [/Users/runner/.dotnet/sdk]
  3.1.302 [/Users/runner/.dotnet/sdk]
  3.1.417 [/Users/runner/.dotnet/sdk] <- skipped
  5.0.102 [/Users/runner/.dotnet/sdk]
  5.0.202 [/Users/runner/.dotnet/sdk]
  5.0.302 [/Users/runner/.dotnet/sdk]
  5.0.406 [/Users/runner/.dotnet/sdk] <- skipped
  6.0.201 [/Users/runner/.dotnet/sdk] <- installed
```

**Windows out of the box (similar for Ubuntu)**

```
.NET SDKs installed:
  3.1.120 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.212 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
```

**Windows after calling `actions/setup-dotnet` (similar for Ubuntu)**

```
.NET SDKs installed:
  3.1.417 [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk] <- installed
  5.0.406 [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk] <- installed
  6.0.201 [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk] <- installed
```

Where's versions 3.1.120, 3.1.202, 3.1.302, 5.0.104, 5.0.212, 5.0.303?

**Comment by vsafonkin** [comment]
Hi @xt0rted, you are absolutely correct, there is pull request with ADR for this problem: https://github.com/actions/setup-dotnet/pull/208

We will try to resolve this issue in future. Since it's known issue, I'm going to close this one. Please, contact with us if you have any concerns, thank you!

**Comment by xt0rted** [comment]
I think a workaround for this is to set the `DOTNET_INSTALL_DIR` environment variable. Doing so skips the versions already installed and preserves those that are installed.

```yml
- run: echo "DOTNET_INSTALL_DIR=/usr/share/dotnet" >> $GITHUB_ENV
  if: matrix.os == 'ubuntu-latest'
  shell: bash

- run: echo "DOTNET_INSTALL_DIR=C:\Program Files\dotnet" >> $GITHUB_ENV
  if: matrix.os == 'windows-latest'
  shell: bash
```

https://github.com/xt0rted-test/setup-dotnet-test/runs/5974572967?check_suite_focus=true#step:6:17

**Comment by PureKrome** [comment]
@vsafonkin That's great news that there's a PR to handle this issue! .. except .. that PR was created in July 2021. That's like 10 months ago! Surely there can be _someone_ to review it?

**Comment by vsafonkin** [comment]
@PureKrome, sure, it was discussed by our team but now it's not priority feature unfortunately.

**Comment by PureKrome** [comment]
Cheers @vsafonkin for the prompt reply - really appreciate it! 🍻 

> it's not priority feature unfortunately.

I'll actually edit your reply, on behalf of a large chunk of the community when they actually read what you're saying:

"It was discussed by our team but _we believe_ .NET is a 3rd class citizen behind all the other cooler langs so no one is going to be bothered. Look, I know it's a simple'ish fix but ... nope. Go learn node then talk to us. kthxbai! 👋🏻 "

sadness :(

**Comment by vsafonkin** [comment]
@PureKrome, our team supports several setup actions and `setup-dotnet` is used almost ten times less than for example `setup-python` or `setup-node`. So the more frequently used actions are considered first.

**Comment by PureKrome** [comment]
@vsafonkin cheers for the reply!

are you (or someone else?) able to list/release top `setup-xxx` actions that are used? Can we see the data to backup these claims? (yes, I believe that there would be more people using python or node over dotnet)

**Comment by xt0rted** [comment]
You can see usage in public repos, but that's it. Action authors can't see usage stats either unfortunately. My guess is `setup-dotnet` is used in a lot of private repos making this number not accurate but who knows. I'm sure there's a fair amount of missed opportunities here with people sticking with Azure DevOps too.

Action | Usage
-- | --:
[setup-node](https://github.com/actions/setup-node/network/dependents?package_id=UGFja2FnZS0yOTQyNTU2NTk1) | 710,438
[setup-python](https://github.com/actions/setup-python/network/dependents?package_id=UGFja2FnZS0yOTQyNTU2NTgy) | 444,788
[setup-java](https://github.com/actions/setup-java/network/dependents?package_id=UGFja2FnZS0yOTQyNTU2NTk0) | 260,679
[setup-go](https://github.com/actions/setup-go/network/dependents?package_id=UGFja2FnZS0yOTQyNTU2NjA5) | 189,716
[setup-dotnet](https://github.com/actions/setup-dotnet/network/dependents?package_id=UGFja2FnZS0yOTQyNTU2NzQw) | 86,306

**Comment by PureKrome** [comment]
Great data @xt0rted !!! Awesome to see the public repo breakdown 👍🏻 👏🏻 

( but I'm crying inside 😢 )

**Comment by mattjohnsonpint** [comment]
An alternative form of [the workaround](https://github.com/actions/setup-dotnet/issues/284#issuecomment-1095162662), if you don't want to run additional steps:

```yaml
env:
  DOTNET_INSTALL_DIR: ${{ startsWith(matrix.os, 'ubuntu') && '/usr/share/dotnet' || startsWith(matrix.os, 'macos') && '/usr/local/share/dotnet' || startsWith(matrix.os, 'windows') && 'C:\Program Files\dotnet' || '' }}
```

**Comment by xt0rted** [comment]
In the end I set up [a composite action](https://github.com/xt0rted/setup-dotnet) that handles this and a few other things that aren't yet supported so it's easier to apply to all of my repos. The workaround was adjusted so it supports all three platforms now:

```yml
- shell: bash
  run: |
    case "${{ runner.os }}" in
      macOS) echo "DOTNET_INSTALL_DIR=/Users/runner/.dotnet" >> $GITHUB_ENV;;
      Linux) echo "DOTNET_INSTALL_DIR=/usr/share/dotnet" >> $GITHUB_ENV;;
      Windows) echo "DOTNET_INSTALL_DIR=C:\Program Files\dotnet" >> $GITHUB_ENV;;
      *) echo "::warning::Unsupported runner os: ${{ runner.os }}";;
    esac
```

**Comment by Piedone** [comment]
With v3 out, shouldn't there no installation happening if the desired version is already installed on the image? I don't see any change in behavior. Running the following under Windows, for example, still takes about 43s, not what I'd expect if it would just use the preinstalled .NET SDK:

```yml
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
```

**Comment by IvanZosimov** [comment]
Hi, @Piedone 👋 Thanks for the question! The latest version of the .NET SDK on the 6.0 channel now is 6.0.402. The latest preinstalled .NET SDK version on our hosted runners is still 6.0.401 ( due to the deployment delays, but it will be updated very soon). That's why when you're specifying `dotnet-version` as 6.0.x you can see the process of downloading and installing .NET 6.0.402 which takes some time. If you specify `dotnet-version` as 6.0.401 which is preinstalled on the runner, `setup-dotnet` will take 1-2 seconds.

**Comment by Piedone** [comment]
Ah, I see, that makes sense, my understanding of the behavior was wrong. Thank you for your quick reply! I can verify that it works faster if I specify a version already installed (<10s vs 15s under Ubuntu, and <25s vs almost 3 minutes under Windows).
