### ISSUE TITLE
Cannot Find hostfxr.dll

### ISSUE THREAD

**Issue by Silvenga** [actions/setup-dotnet#29]
Not completely sure if related to this action, but my best guess the issue is related to https://github.com/actions/setup-dotnet/pull/12#issuecomment-519660629.

```
Using: actions/setup-dotnet@v1.1.0
```

```
Run wyam
  wyam
   shell: C:\Program Files\PowerShell\6\pwsh.EXE -command ". '{0}'"
  env:
    DOTNET_ROOT: C:\hostedtoolcache\windows\dncs
A fatal error occurred, the required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\runneradmin\.dotnet\tools\.store\wyam.tool\2.2.4\wyam.tool\2.2.4\tools\netcoreapp2.1\any\].
If this is a framework-dependent application, install the runtime in the default location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```

**Comment by JSkimming** [comment]
I have a similar issue, try downgrading to v1.0.2

```
uses: actions/setup-dotnet@v1.0.2
```

The only difference between [v1.0.2 and v1.1.0](https://github.com/actions/setup-dotnet/compare/v1.0.2...v1.1.0) is the change you have identified.

**Comment by Silvenga** [comment]
@JSkimming I believe that `DOTNET_ROOT` variable is required for global tools to launch, I'm just wondering if it's set to the wrong path.

**Comment by JSkimming** [comment]
@Silvenga, yeah I wondered that. I'm going to experiment later to find out.

**Comment by JSkimming** [comment]
@Silvenga I think the location the SDK is installed is incorrect, (the environment variable my also need changing).

On my machine, I get the following from `dotnet --info`

```
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
```

for which `DOTNET_ROOT` should be set to `C:\Program Files\dotnet\sdk`, here's the same output from an action:

```
> dotnet --info
 .NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /opt/hostedtoolcache/dncs/2.2.401/x64/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [/opt/hostedtoolcache/dncs/2.2.401/x64/sdk]
```

On my machine, I have three SDKs, all installed to the same version-independent location. I assume the SDK installer takes care of side-by-side installs.

Therefore I suspect the this `setup-dotnet` action should install the SDK in a version independent path, instead of `/opt/hostedtoolcache/dncs/2.2.401/x64/sdk/`.

**Comment by biom3tric** [comment]
Using v1.1.0, i had to do this to make global tools work
```
export PATH="$PATH:$HOME/.dotnet/tools"
export DOTNET_ROOT=$DOTNET_ROOT/2.2.401/x64/
```

The default DOTNET_ROOT variable stops to `/opt/hostedtoolcache/dncs/`, instead of going into the version and x64 folder

**Comment by Silvenga** [comment]
Thanks for the confirmation @biom3tric - I feel like the default should have worked as this change was made - https://github.com/actions/setup-dotnet/pull/12/commits/ff36c3f74808c58fe86e008c9df007eb630ffbf6 (updated `DOTNET_ROOT` to be `/opt/hostedtoolcache/dncs/` instead of `/opt/hostedtoolcache/dncs/version/arch/`).

@damccorm it seems we need to be pointing to the versioned folder - the cli for 2.1 and 2.2 sdk's don't know how to resolve the correct version.

**Comment by rmunn** [comment]
I can also confirm that the DOTNET_ROOT value should have been `/opt/hostedtoolcache/dncs/version/arch/`, and that reverting https://github.com/actions/setup-dotnet/commit/ff36c3f74808c58fe86e008c9df007eb630ffbf6 should resolve this. Here's what I get when I do `ls -l /usr/share/dotnet/` (the default .Net Core installation location, which it will use if `DOTNET_ROOT` is not set) on my development machine:
```plaintext
total 148
-rwxr-xr-x 1 root root 105704 Jun 19 03:03 dotnet
drwxr-xr-x 3 root root   4096 May 30 02:25 host
-rw-r--r-- 1 root root   1083 Jun 19 03:03 LICENSE.txt
drwxr-xr-x 4 root root   4096 Aug  2 19:57 sdk
drwxr-xr-x 5 root root   4096 May 30 02:25 shared
-rw-r--r-- 1 root root  27700 Jun 19 03:03 ThirdPartyNotices.txt
```

And here's the first part of an `ls -lR /opt/hostedtoolcache/dncs` after running the `setup-dotnet` action:

```plaintext
/opt/hostedtoolcache/dncs:
total 4
drwxrwxrwx+ 3 runner docker 4096 Sep  4 04:43 2.2.401

/opt/hostedtoolcache/dncs/2.2.401:
 total 4
drwxrwxrwx+ 5 runner docker 4096 Sep  4 04:43 x64
-rw-rw-rw-+ 1 runner docker    0 Sep  4 04:43 x64.complete

/opt/hostedtoolcache/dncs/2.2.401/x64:
total 148
-rw-r--r--+ 1 runner docker   1083 Sep  4 04:43 LICENSE.txt
-rw-r--r--+ 1 runner docker  27700 Sep  4 04:43 ThirdPartyNotices.txt
-rwxr-xr-x+ 1 runner docker 105872 Sep  4 04:43 dotnet
drwxr-xr-x+ 3 runner docker   4096 Sep  4 04:43 host
drwxr-xr-x+ 4 runner docker   4096 Sep  4 04:43 sdk
drwxr-xr-x+ 5 runner docker   4096 Sep  4 04:43 shared
```

Clearly, `/opt/hostedtoolcache/dncs/2.2.401/x64` contains the files that .Net Core expects to see in its `DOTNET_ROOT`.

As an additional confirmation, changing `DOTNET_ROOT` from `/opt/hostedtoolcache/dncs/` to `/opt/hostedtoolcache/dncs/2.2.401/x64` made the build [work in my test repo](https://github.com/rmunn/Testing/pull/7/checks?check_run_id=211465392).

**Comment by gitfool** [comment]
Same issue here. Worked on Windows. Failed on Linux and Mac unless I override `DOTNET_ROOT`.

**Comment by adamralph** [comment]
For .NET SDK 3.0.100 (RTM) it also does not work on Windows. See https://github.com/adamralph/bullseye/pull/353

**Comment by adamralph** [comment]
Using .NET SDK 3.0.100 (RTM), even if I apply the fix of setting `DOTNET_ROOT` to `$DOTNET_ROOT/3.0.100/x64` then I get:

> It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
>   - Check application dependencies and target a framework version installed at:
>       /usr/share/dotnet
>   - Installing .NET Core prerequisites might help resolve this problem:
>       https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
>   - The .NET Core framework and SDK can be installed from:
>       https://aka.ms/dotnet-download
>   - The following versions are installed:
>       2.1.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
>       2.1.1 at ...

See https://github.com/adamralph/bullseye/runs/235426018

**Comment by adamralph** [comment]
This is not so important anymore, since the images now have 3.0.100 installed, so there is no need to use `setup-dotnet` to install that version of the SDK.

**Comment by adamralph** [comment]
...but 3.0.100 is only installed on the Windows images. 😭

**Comment by rmunn** [comment]
I had a [successful run of my test workflow](https://github.com/rmunn/Testing/runs/241012126) with the .Net Core 3.0 SDK (version 3.0.100), but I'm not trying to build against the `netcoreapp3.0` target in that workflow, so that doesn't prove that @adamralph's problem is fixed. All it proves is that `/opt/hostedtoolcache/dncs/{DOTNET_VERSION}/{ARCHITECTURE}` is still the right setting for the `DOTNET_ROOT` variable in .Net Core 3.0.

**Comment by gitfool** [comment]
Yeah, the workaround is still needed; confirmed after I re-targeted to .NET Core 3.0 SDK:

- https://github.com/gitfool/cake-docker/runs/240897568#step:6:33 ([bf12ebf](https://github.com/gitfool/cake-docker/commit/bf12ebf73015d3d2d803764adbcd74efb26e451f) fails)
- https://github.com/gitfool/cake-docker/runs/240955048#step:6:33 ([39ac563](https://github.com/gitfool/cake-docker/commit/39ac563871505ba8013e97fc4144b87af330d3cc) succeeds)

**Comment by adamralph** [comment]
Even with the `DOTNET_ROOT` workaround, if you try and _run_ a .NET Core 3.0 console app with `dotnet run`, it still fails: https://github.com/adamralph/bullseye/runs/235426018#step:7:53

**Comment by adamralph** [comment]
BTW it seems that the `dotnet run` problem is specific to 3.0.100, so it may be better to discuss that in https://github.com/actions/setup-dotnet/issues/40

**Comment by 3ventic** [comment]
FWIW adding the `DOTNET_ROOT` workaround worked for me for `dotnet run` too:
```
     run:
        export DOTNET_ROOT="$DOTNET_ROOT/${{ matrix.dotnet }}/x64/"
        dotnet restore
        dotnet build
        dotnet run -- -h
```

**Comment by roji** [comment]
Is this already fixed but simply waiting to be released? If so please consider doing that soon, it must be causing quite a few headaches out there...

**Comment by adamralph** [comment]
@roji are you pinning to a specific commit? If so, you just need to update to a version which contains the fix. E.g.

```yaml
- uses: actions/setup-dotnet@bb95ce727fd49ec1a65933419cc7c91747785302
```

**Comment by roji** [comment]
Thanks for the tip, am still starting out with GA and didn't know that was possible.

However, this really should still be released ASAP - I'm sure there are many out there pinning to the latest release (1.1.0) and stumbling over this.

**Comment by adamralph** [comment]
Fair point.
