### ISSUE TITLE
Question: Is there a way to test .NET framework 4.6.1+

### ISSUE THREAD

**Issue by Ygg01** [actions/setup-dotnet#296]
**Description:**
I want to test my package for .NET 4.6.1 environments. https://github.com/Ygg01/Linguini

**Justification:**
Another app wants to depend on this package and I'd be a bit more secure that a future change won't mess up compatibility.

**Comment by vsafonkin** [comment]
Hi @Ygg01, GitHub Windows runners already have installed .NET Framework, for example .NET Framework version 4.8 on the `windows-2022` runner: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#net-framework

.NET Framework has backward compatibility with older versions.

You can install either .NET Core (for example 3.1) or .NET (for example 5.0) versions via `setup-dotnet` action, not .NET Framework.

**Comment by Ygg01** [comment]
Aha, I see, so I can run `4.6.1` framework tests from .NET 5.0 via `dotnet test -f net461`

**Comment by OZZlE** [comment]
Our internal github only supports "runs-on: linux-(something)" and "uses: actions/setup-dotnet" and inside setup-dotnet you seem to only be able to pick .Net Core versions.. will this really work with .Net Framework (4.72) ??

**Comment by IvanZosimov** [comment]
Hi, @OZZlE 👋, thanks for the question! The `setup-dotnet` indeed installs .NET Core / .NET versions only, if you have to make .NET Framework app work with .NET Core / .NET you need to [port](https://docs.microsoft.com/en-us/dotnet/core/porting/) your app or try to install and use [Mono project](https://www.mono-project.com). Another way to solve the issue (if it suits you) - using our 'windows-latest' or 'windows-2019' runner images which already include  .NET Framework version installed.

**Comment by Mohsen8136** [comment]
به نام حق که بخشنده و مهربان هست جزو اصلیترین صفتهایش در ۱۱۳ سوره   ابتدا
دعا کنید بی ریا و از حضرت حق آرزوی توفیق در گرامی داشت این بانوی عزیز و
عزیزانش که عزیزان شما محسوب میشوند. قدم اول وظیفه دادستان کشور این هست و
باید باشد که فردی که تهدید کرده این عزیز را و مسبب اصلی هست را در برابر
دوربین و با صورت کاملا مشخص توضیح دهد که آیا آموزش دیده بوده یا نه..واز کار
تعلیق و پرونده را کاملا روشن و بهتر حرکت دهید..هر کس شغلش قدم دوم همگان
دعوت به آرامش و گلهای زیاد از هوا و زمین بر شهرها فرود آید و گرازهای
خیابانی جمع شوند و خادمین مردم در لباس عادی و شال سیاه در شغل خود حاضر شده
و سر را پایین نگه دارند و آماده کتک خوردن هم باشند بدون پاسخ ..دستور ۳م۹
ثبت پخش اجرا  بسازید خراب نکنید  آباد کنید ویران نکنید ستم نکنید شما از چه
سفره نان خردید از کدام اصول برخورداری؟کدام خدا را قبول داری؟لعنت و نفرین
نکن دعا کن بساز گراز رو تبدیل به ماهی کن دعوا نکن دعوت کن شعار نده شعر بگو

در تاریخ جمعه ۲۶ اوت ۲۰۲۲،‏ ۱۲:۳۳ Oskar ***@***.***> نوشت:

**Comment by Mohsen8136** [comment]
به نام حق که بخشنده و مهربان هست جزو اصلیترین صفتهایش در ۱۱۳ سوره   ابتدا
دعا کنید بی ریا و از حضرت حق آرزوی توفیق در گرامی داشت این بانوی عزیز و
عزیزانش که عزیزان شما محسوب میشوند. قدم اول وظیفه دادستان کشور این هست و
باید باشد که فردی که تهدید کرده این عزیز را و مسبب اصلی هست را در برابر
دوربین و با صورت کاملا مشخص توضیح دهد که آیا آموزش دیده بوده یا نه..واز کار
تعلیق و پرونده را کاملا روشن و بهتر حرکت دهید..هر کس شغلش قدم دوم همگان
دعوت به آرامش و گلهای زیاد از هوا و زمین بر شهرها فرود آید و گرازهای
خیابانی جمع شوند و خادمین مردم در لباس عادی و شال سیاه در شغل خود حاضر شده
و سر را پایین نگه دارند و آماده کتک خوردن هم باشند بدون پاسخ ..دستور ۳م۹
ثبت پخش اجرا  بسازید خراب نکنید  آباد کنید ویران نکنید ستم نکنید شما از چه
سفره نان خردید از کدام اصول برخورداری؟کدام خدا را قبول داری؟لعنت و نفرین
نکن دعا کن بساز گراز رو تبدیل به ماهی کن دعوا نکن دعوت کن شعار نده شعر بگو

در تاریخ شنبه ۱۷ سپتامبر ۲۰۲۲،‏ ۱۴:۳۹ Mohsen Parvandi <
***@***.***> نوشت:
