### ISSUE TITLE
How to include wasm-tools?

### ISSUE THREAD

**Issue by Aloento** [actions/setup-dotnet#304]
**Description:**
It's possible to add the wasm-tools in the actions?

**Justification:**

This is what I am currently using.

```yarn
- name: Set up .NET Core
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: "7.0.x"
    include-prerelease: true

- run: dotnet workload install wasm-tools
```

**Comment by e-korolevskii** [comment]
Hello @Aloento!

I think we are probably not going to do it. In general, the pattern we are looking for here (and with activities in general) is to align CI as much as possible with the developer experience. In particular, the purpose of this action is to install `.Net`. Adding `wasm-tools` to the action has no clear advantages over how you set them now (it won't speed up CI), but may have negative consequences, besides, we are not sure that all clients using this action will need it.

Now I will close this issue, but if you have additional questions or suggestions, you can leave them here or in a new issue. Have a good day!
