### ISSUE TITLE
Add option to disable error matcher

### ISSUE THREAD

**Issue by flobernd** [actions/setup-dotnet#309]
**Description:**

There should be an input option to disable the error matcher.

**Justification:**

The default error matcher interferes, if you want to use a third-party matcher which e.g. filters out certain warnings.

Edit:
I'm aware of the `echo "::remove-matcher owner=csc::"` possibility. Would just be more convenient with a proper input.

**Comment by IvanZosimov** [comment]
Hi, @flobernd 👋 Thank you for the feature request, we will take a look at that idea and get back to you with some updates.

**Comment by anthony-c-martin** [comment]
Having simpler control over this would be great. Our build pipeline uses a matrix to build against multiple targets, so we end up with heavily duplicated errors if there's a build failure - this gets in the way of reviewing:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/38542602/235694583-2da85437-41fd-461d-92e0-4d06d2a0cef1.png">

Here's the build definition: https://github.com/Azure/bicep/blob/23ebbef0450e7c1c80a2b55ac9fa1c1fd8b7c011/.github/workflows/build.yml#L53-L54

**Comment by flobernd** [comment]
I created a wrapper around the "official" action as a workaround for now..

https://github.com/zyactions/dotnet-setup

Feel free to use it!

I personally still would prefer a switch in the official action.

**Comment by IvanZosimov** [comment]
Hi, @flobernd 👋 Unfortunately we have to reject this feature request, because of the existence of the official mechanism to turn off matchers in GitHub actions. Moreover, this feature request leads to adding a new input that adds complexity to the action.

**Comment by flobernd** [comment]
Hi @IvanZosimov, no problem 🙂 

I havn't checked, if it's documented somewhere specifically for this action, but if not, that might be something to consider. A lot of people do not know about the `remove-matcher` function and using it as well requires to check the action source to determine the correct `owner` name to use (like `csc` in this case).
