### ISSUE TITLE
Action failing to execute powershell with -Sta param

### ISSUE THREAD

**Issue by ukphillips** [actions/setup-dotnet#325]
**Description:**
Action started failing after the latest release due to the version of powershell used

**Task version:**
V2

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
Run the task as it was working previously on a self hosted windows agent

**Expected behavior:**
Expected .NET to be installed successfully

**Actual behavior:**
Powershell failed:

Run actions/setup-dotnet@v2
"C:\Program Files\PowerShell\6\pwsh.exe" -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\actions-runner-deploy-1\_work\_actions\actions\setup-dotnet\v2\externals\install-dotnet.ps1' -Version 3.1.423"
The argument '-Sta' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

The new release changed the path of powershell used (now version 6), and does not handle the -Sta param

**Comment by IvanZosimov** [comment]
Hi, @ukphillips 👋 Thanks for getting our attention to it, we will take a look and get back to you with updates.

**Comment by IvanZosimov** [comment]
@ukphillips, I believe updating the PowerShell version to LTS (take a look at the PowerShell [lifecycle](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.2))  will solve your problem. PowerShell 6.0 lacks some line options (compared to Windows PowerShell (1.0 - 5.1)), but MS fixed it in 7+ versions.

**Comment by ukphillips** [comment]
@IvanZosimov this did seem to resolve the problem. After the install the task succeeds with the following output:

Run actions/setup-dotnet@v2
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\actions-runner-build-2\_work\_actions\actions\setup-dotnet\v2\externals\install-dotnet.ps1' -Version 3.1.423"
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

I guess I'm not sure why it looks like its still falling back to <6 version of powershell, but it does look like it is working properly.
