### ISSUE TITLE
v3 tag missing

### ISSUE THREAD

**Issue by martincostello** [actions/setup-dotnet#328]
There is no `v3` tag in the repository pointing to the same commit as the `v3.0.0` tag.

This causes dependabot to create version bump PRs from `v2` to `v3.0.0` instead of to `v3`.

**Comment by IvanZosimov** [comment]
Hi, @martincostello 👋 Thank you for taking our attention to that issue, now `v3` tag is available. 
I'm going to close this issue, If you have any additional questions, feel free to ping us.
