### ISSUE TITLE
Warning in workflow about set-output

### ISSUE THREAD

**Issue by leandromsft** [actions/setup-dotnet#334]
**Description:**
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

![image](https://user-images.githubusercontent.com/69152421/195376016-190344e2-0aba-4618-915c-74a69cf29721.png)

**Task version:**
V3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Comment by IvanZosimov** [comment]
Hi, @leandromsft 👋 Thanks for the issue, we are currently working on it.

**Comment by ianong-rsi** [comment]
Hi @IvanZosimov. This warning also appears in other actions such as `actions/download-artifact@v3`, `actions/setup-java@v3`, etc.. Will the resolution be applied to all?

**Comment by IvanZosimov** [comment]
Hi, @ianong-rsi 👋 For the `actions/setup-java` it definitely will in the next version release. For the `actions/download-artifact` I'm suggesting you create an issue in their repo to be 100% sure.

**Comment by christina-30** [comment]
@leandromsft @IvanZosimov Hi I also have heaps of waring from "set-out" command issue.
![Screen Shot 2022-10-14 at 2 23 45 pm](https://user-images.githubusercontent.com/112351798/195758698-5c52980f-9a42-4c30-bf5c-4dd7309c6816.png)

**Comment by IvanZosimov** [comment]
Hi, @christina-30 👋 From your message it's not possible to see which actions exactly produced these warnings. I suggest you to check the repo for each action that warns and if there is no issue related to that warning - create it there 😉

**Comment by IvanZosimov** [comment]
@leandromsft, I'm going to close this issue now, because the new patch version of the action was released and it solves the problem with the warning. If you have any additional questions, feel free to ping us.
