### ISSUE TITLE
Support for installing latest patch

### ISSUE THREAD

**Issue by manfred-brands** [actions/setup-dotnet#339]
**Description:**
Allow specifying a way to only update patches, e.g. from 6.0.200 to 6.0.201 but not to 6.0.300.
Either using an option like the global json (rollForward: latestPatch), or using the 6.0.2xx specification.

**Justification:**
Some .NET SDK updates, e.g. from 6.0.200 to 6.0.300 cause compile errors due to small changes in compiler or nuget tools.

**Are you willing to submit a PR?**
Yes, if proposal is accepted.

**Comment by marko-zivic-93** [comment]
Hello @manfred-brands 
Thank you for your feature request. We will investigate it and come back to you with our decision about it :)

**Comment by IvanZosimov** [comment]
Hi, @manfred-brands 👋 We just merged the pull request https://github.com/actions/setup-dotnet/pull/428 which adds support for `A.B.Cxx` syntax. It's not released yet as a tag, but you can try it using this syntax:
``` yaml
- uses: actions/setup-dotnet@main
```
If you have any questions, feel free to ping me.

**Comment by manfred-brands** [comment]
Thanks, much appreciated.
