### ISSUE TITLE
Verify if requested version exists before attempting to install

### ISSUE THREAD

**Issue by timheuer** [actions/setup-dotnet#343]
**Description:**
When using the setup action, you specify a `dotnet-version`.  If the runner being used already has the requested version (or pattern-matched version) then there really is no need to continue trying to install again and it should succeed, printing out the version found.

**Justification:**
Saves time in CI runs for users (and thus saves them money :-))

**Comment by IvanZosimov** [comment]
Hi, @timheuer 👋 Thank you for that feature request! In the recent major release [v3](https://github.com/actions/setup-dotnet/tree/v3) this feature was added to the action. 

By now I'm going to close this issue, if you have any additions feel free to ping me.

**Comment by timheuer** [comment]
Oh nice! The logs seem to indicate that it is still executing the download script.

-th
________________________________

**Comment by IvanZosimov** [comment]
@timheuer, the action under the hood uses the [official .NET installer scripts](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script). These scripts check whether the required .NET version is installed on the machine and exit installation in case the required version is found. Probably in the logs you see that action executes this official script.
