### ISSUE TITLE
Dotnet version is always 6

### ISSUE THREAD

**Issue by tomarad** [actions/setup-dotnet#346]
**Description:**
Even when specifying a version with `dotnet-version`, dotnet version is still 6.

**Task version:**
3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Check out [this](https://github.com/tomarad/setup-dotnet-bug) repo and these runs: [version 2](https://github.com/tomarad/setup-dotnet-bug/actions/runs/3463207148/jobs/5783118573), [version 3](https://github.com/tomarad/setup-dotnet-bug/actions/runs/3463207142/jobs/5783119093).

**Expected behavior:**
`dotnet --version` should print the version from the parameter.

**Actual behavior:**
`dotnet --version` prints 6.0.402.

**Comment by IvanZosimov** [comment]
Hi, @tomarad 👋 Thanks for the bug report! The new major version `v3` of our action brought some [breaking changes](https://github.com/actions/setup-dotnet/blob/main/docs/adrs/v3-setup-dotnet.md#breaking-changes) and the behaviour that you described is completely expected. The `dotnet --version` command print out the latest version installed on the runner and, by the way, this version is default. If you want to change `default` version to `3.0.103`, you need to [change](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) your `global.json` file accordingly.

By now, I'm going to close this issue, If you have any additional questions feel free to ping me.

**Comment by tomarad** [comment]
Thanks @IvanZosimov, my bad :sweat_smile:.
