### ISSUE TITLE
dotnet-setup

### ISSUE THREAD

**Issue by Mar181-arc** [actions/setup-dotnet#366]
**Description:**
Describe your proposal.

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

**Comment by IvanZosimov** [comment]
I'm closing this issue as a spammy one.

**Comment by Eryk1705** [comment]
Em sex., 6 de jan. de 2023 16:56, Mar181-arc ***@***.***>
escreveu:
