### ISSUE TITLE
Access denied after update from v2 to v3 on self-hosted runner

### ISSUE THREAD

**Issue by Michaelschnabel-DM** [actions/setup-dotnet#380]
**Description:**
After the update from v2 to v3 the self hosted runner has issues accessing the file C:\Program Files\dotnet\dotnet.exe, with version 2 everything worked fine.

**Task version:**
v3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
Repo is private

**Expected behavior:**
-

**Actual behavior:**
-

![image](https://user-images.githubusercontent.com/97694159/218434841-551c1ce6-cea1-456f-a79c-ac1b9f05ac09.png)
![image](https://user-images.githubusercontent.com/97694159/218434973-c127fd51-ae42-48ae-a3cf-1b5576608905.png)

**Comment by panticmilos** [comment]
hi @Michaelschnabel-DM, thank you for the report we will take a look at it.

**Comment by dmitry-shibanov** [comment]
Hello @Michaelschnabel-DM. Could you please try to use this snippet before `actions/setup-dotnet`:
```yaml
      - run: |
          $pwshPath = which pwsh
          Write-Host $pwshPath >> $env:GITHUB_PATH
```
Besides, could you please try to change default PowerShell on PowerShell Core (pwsh) on your self-hosted?

**Comment by 134130** [comment]
Same problem on linux self-hosted. 
I upgraded setup-dotnet from v2 to v3.
```
mkdir: cannot create directory '/usr/share/dotnet': Permission denied
```

**Comment by Michaelschnabel-DM** [comment]
Hi all, specifying the DOTNET_INSTALL_DIR worked for me: 
![image](https://user-images.githubusercontent.com/97694159/221793994-ffa51068-f044-4431-8c61-e629a931b06f.png)

**Comment by MartinBarkerPhilips** [comment]
> Hi all, specifying the DOTNET_INSTALL_DIR worked for me: ![image](https://user-images.githubusercontent.com/97694159/221793994-ffa51068-f044-4431-8c61-e629a931b06f.png)

where did you add this var ?I am facing the same issue

**Comment by daniel18acevedo** [comment]
@MartinBarkerPhilips  https://github.com/actions/setup-dotnet?tab=readme-ov-file#environment-variables
