### ISSUE TITLE
Selecting dotnet-version: '2.1.802' with action, but having '2.2.105' on dotnet run commands

### ISSUE THREAD

**Issue by magicben** [actions/setup-dotnet#39]
I created an action containing this YML definition part:

> jobs:
>   build:
>     runs-on: windows-latest
>     
>     steps:
>     - uses: actions/setup-dotnet@v1
>       with:
>         dotnet-version: '2.1.802'
>     - run: |
>         dotnet --version
>         dotnet --info

The result of:
>     - run: |
>         dotnet --version
>         dotnet --info

Is the following (some parts are truncated below):
> dotnet --version
> 2.2.105
> .NET Core SDK (reflecting any global.json):
>  Version:   2.2.105
>  Commit:    7cecb35b92
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17763
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.2.105\
> 
> Host (useful for support):
>   Version: 2.1.13
>   Commit:  1a165a1588
> 
> .NET Core SDKs installed:
>   1.0.1 [C:\Program Files\dotnet\sdk]
>   1.0.4 [C:\Program Files\dotnet\sdk]
>   1.1.4 [C:\Program Files\dotnet\sdk]
>   1.1.5 [C:\Program Files\dotnet\sdk]
[... truncated part ...]
>   Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by ZEisinger** [comment]
Please take a look at #10 for context on disabling multilevel lookup, which used a 2.1.* version in my test.
To disable the multilevel look up you can add this to the action
```
    env:
      DOTNET_MULTILEVEL_LOOKUP: 0
```
or set the environment variable.
```
run: ##[set-env name=DOTNET_MULTILEVEL_LOOKUP]0
```

Please reopen if that does not solve the problem.
