### ISSUE TITLE
3.0.100 does not work

### ISSUE THREAD

**Issue by adamralph** [actions/setup-dotnet#40]
The first problem is https://github.com/actions/setup-dotnet/issues/29

But even after using the workaround listed there, another problem is encountered:

```
dotnet run -c Release --no-build -p BullseyeSmokeTester -- --help
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
...
```

Repro at https://github.com/adamralph/bullseye/runs/238588806

Changeset: https://github.com/adamralph/bullseye/pull/353/files

**Comment by VahidN** [comment]
Try adding the `global.json` file to the root folder of the project.
```json
{
  "sdk": {
    "version": "3.0.100"
  }
}
```

**Comment by adamralph** [comment]
@VahidN that makes no difference: https://github.com/adamralph/bullseye/runs/238613154

The SDK already knows that the `3.0.100` runtime should be used. It just can't find it on disk. I suspect this related to the fact that `setup-dotnet` puts it in a strange location:

```
.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/opt/hostedtoolcache/dncs/3.0.100/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/opt/hostedtoolcache/dncs/3.0.100/x64/shared/Microsoft.NETCore.App]
```

**Comment by adamralph** [comment]
This is not so important anymore, since the images now have 3.0.100 installed, so there is no need to use `setup-dotnet` to install that version of the SDK.

**Comment by adamralph** [comment]
...but 3.0.100 is only installed on the Windows images. 😭

**Comment by NickCraver** [comment]
FWIW, this is ultimately the same cause of #25 - the install locations aren't compatible with what .NET generally expects for side-by-side.

**Comment by adamralph** [comment]
FTR `ubuntu-16.04`, `ubuntu-18.04`, and `windows-2019` now all have `3.0.100` installed.

Just `macOS-10.14` and `windows-2016` still to come...

**Comment by adamralph** [comment]
Can we get this fixed? I'm not sure how long it will take `macOS-10.14` to get `3.0.100`, and I'm not sure `windows-2016` will ever get it.

**Comment by NickCraver** [comment]
If it helps, this is also blocking all of my use cases, unfortunately (libraries need to test against multiple runtimes - it's quite common). I'd love to test out Actions and get it set up for all of our OSS projects (they're ready to go in PR form at the moment - pending this).

**Comment by adamralph** [comment]
@chkimes @ZEisinger thank you so much! It works perfectly now.
