### ISSUE TITLE
How do I install 7.0.400 preview

### ISSUE THREAD

**Issue by nojaf** [actions/setup-dotnet#413]
**Description:**
Hello, I'm very confused about how I can install the latest `7.0.400-preview`.

**Task version:**
3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
When I list `dotnet-quality` as `preview` or `daily` I cannot specify the `400` part.
And so that keeps downloading `7.0.202` stable

**Expected behavior:**
I want to have the same version as https://aka.ms/dotnet/7.0.4xx/daily/dotnet-sdk-win-x64.exe would give me.

**Actual behavior:**
Not sure how to do this or it downloads the stable 7 version.

**Comment by IvanZosimov** [comment]
Hi, @nojaf 👋 Thank you for the issue! By now it's not possible to use the latest patch version syntax with setup-dotnet, so unfortunately our action can't download the version from https://aka.ms/dotnet/7.0.4xx/daily/dotnet-sdk-win-x64.exe. We are working on this feature now, you can check the progress in this issue https://github.com/actions/setup-dotnet/issues/382.
