### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by brian-pickens** [actions/setup-dotnet#420]
**Description:**
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-dotnet@v1.7.2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Task version:**
1.7.2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
Simply run the action

**Expected behavior:**
The action uses Node 16

**Actual behavior:**
The action uses Node 12

**Comment by nogic1008** [comment]
@brian-pickens 
please use [v2](https://github.com/actions/setup-dotnet/releases/tag/v2.0.0) or higher

**Comment by IvanZosimov** [comment]
Hi, @brian-pickens 👋 As @nogic1008 stated, please use up-to-date version of `setup-dotnet`. Currently it's `v3`.
I'm going to close this issue now, If you have any additional questions feel free to ping me.
