### ISSUE TITLE
Return

### ISSUE THREAD

**Issue by soenaing431** [actions/setup-dotnet#454]
otpauth://totp/goigle%3Aotpauth%3A//hotp/google%253Agoogle%3Fsecret%3DVJNMQOTDYWLHK%26issuer%3Dgoogle%26algorithm%3DSHA256%26digits%3D6%26counter%3D31?secret=OTPAUTHHOTPGOOGLE3AGOOGLEQ&issuer=goigle&algorithm=SHA1&digits=6&period=30

**Comment by IvanZosimov** [comment]
Closed as spam.
