### ISSUE TITLE
Add support for .net 8 

### ISSUE THREAD

**Issue by kaypee90** [actions/setup-dotnet#457]
**Description:**
Add support for .net 8. Currently getting this error `Error: Could not find dotnet core version. Please ensure that specified version 8.0.x is valid.`

**Comment by IvanZosimov** [comment]
Hi, @kaypee90 👋 Unfortunately, I couldn't reproduce the problem. The action has already supported .NET 8. You can see it in my test [runs](https://github.com/IvanZosimov/TestRepo2/actions/runs/6034321634).

**Comment by kaypee90** [comment]
@IvanZosimov I was experiencing this issue because I was referencing `actions/setup-dotnet@v2` instead of `actions/setup-dotnet@v2` and I found out from the sample you shared thanks.
