### ISSUE TITLE
Deprecation warning due to Node 16

### ISSUE THREAD

**Issue by Piedone** [actions/setup-dotnet#478]
**Description:**
Node 16 is [now deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Because of this, when using this action, you'll see warnings like below under your workflow runs:

![image](https://github.com/actions/setup-dotnet/assets/1976647/6cf63f1f-86fd-40f1-9e3d-91de7d2a3fe6)

**Task version:**
v3.2.0

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  
Any usage of this action.

**Expected behavior:**
No deprecation warning is displayed.

**Actual behavior:**
Deprecation warning is displayed.

**Comment by dusan-trickovic** [comment]
Hello, @Piedone! Thank you for creating this issue. We will look into it and see what can be done :)

**Comment by Piedone** [comment]
Thank you!

**Comment by Salm3** [comment]
> **الوصف: تم **[الآن إهمال](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) العقدة 16 . ولهذا السبب، عند استخدام هذا الإجراء، سترى تحذيرات كما هو موضح أدناه ضمن عمليات تشغيل سير العمل:[](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)
> 
> ![صورة](https://user-images.githubusercontent.com/1976647/277830168-6cf63f1f-86fd-40f1-9e3d-91de7d2a3fe6.png)
> 
> **إصدار المهمة:** v3.2.0
> 
> **منصة:**
> 
> * [x] أوبونتو
> * [x] ماك
> * [x] شبابيك
> 
> **نوع العداء:**
> 
> * [x] مستضاف
> * [x] استضافة ذاتية
> 
> **خطوات إعادة الإنتاج:** أي استخدام لهذا الإجراء.
> 
> **السلوك المتوقع:** لم يتم عرض أي تحذير بالإهمال.
> 
> **السلوك الفعلي:** يتم عرض تحذير الإهمال.

#471

**Comment by rdipardo** [comment]
This can be closed since #484 has been merged into `main`.

**Comment by dmitry-shibanov** [comment]
Hello everyone. The new version of setup-dotnet with support of Node 20 was released in [v4.0.0](https://github.com/actions/setup-dotnet/releases/tag/v4.0.0). For now I'm going to close the issue.
