### ISSUE TITLE
Renaming the task version of the Program

### ISSUE THREAD

**Issue by Chitochat15** [actions/setup-dotnet#496]
**Description:**

**Task version:**
Specify the task version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by Nancy78251** [comment]
Nancy Mireles

**Comment by Nancy78251** [comment]
💖

Nancy reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by Nancy78251** [comment]
💖

Nancy reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>
