### ISSUE TITLE
.NET MAUI IOS

### ISSUE THREAD

**Issue by Kebechet** [actions/setup-dotnet#512]
**Description:**

`actions/setup-dotnet@v4` caused my .NET MAUI pipeline to crash (only ios build). The error was: 

> Error: /Users/runner/work/SatisFIT/SatisFIT/src/Client/SatisFIT.Client.App/Platforms/iOS/AppDelegate.cs(9,28): error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/SatisFIT/SatisFIT/src/Client/SatisFIT.Client.App/SatisFIT.Client.App.csproj::TargetFramework=net8.0-ios]

it works correctly with `v3`.
Installed SDK: 8.0.102

**Task version:**
v4

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
N/A

**Expected behavior:**
The build of maui app should finish successfully

**Actual behavior:**
Task fails with error

**Comment by HarithaVattikuti** [comment]
Hello @Kebechet 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by priyagupta108** [comment]
Hello @Kebechet 👋,
The error indicates that MauiUIApplicationDelegate cannot be found, which is a part of .NET MAUI. Please ensure that all .NET MAUI dependencies and SDKs are properly installed and set up in your build environment.
To help us further investigate the issue, Could you please attach link to the build or public repository to reproduce the issue.

**Comment by Kebechet** [comment]
Hello @priyagupta108 
I have updated everything to latest versions
**.net sdk:** `8.0.202`
**maui:** `8.0.14`
**actions/setup-dotnet:** `v4`

and everything seems to be working correctly. Closing. 
Thank you for your time.
