### ISSUE TITLE
cache-dependency-path does not support list of file names, but in description it's said, thay it can

### ISSUE THREAD

**Issue by Denyyyys** [actions/setup-dotnet#536]
**Description:**
In the [action.yml](https://github.com/actions/setup-dotnet/blob/main/action.yml) there is part of information:
`cache-dependency-path:
    description: 'Used to specify the path to a dependency file: packages.lock.json. Supports wildcards or a list of file names for caching multiple dependencies.'
    required: false
`
When I try to add pathes to a couple of packages.lock.json files, for example as ["./backend/WebServer", "./backendTest"], then I got error in my Github Actions I got error with message: `Invalid type found: one of string , number , boolean were expected but an array was found`. 

**Task version:**
actions/setup-dotnet@v4

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Self-hosted
- [ ] hosted

**Repro steps:**  
create your own action. Add job with steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        cache: true
        cache-dependency-path: ["./backend/WebServer", "./backendTest"]

**Expected behavior:**
To take into account a couple of packages.lock.json files from ./backend/WebServer and ./backendTest

**Actual behavior:**
Getting error message: `Invalid type found: one of string , number , boolean were expected but an array was found`.

**Comment by priya-kinthali** [comment]
Hello @Denyyyys 👋,
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by suyashgaonkar** [comment]
Hi @Denyyyys, we did had look into this and we see that cache-dependency-path does not accept multiple paths in a array. You can try by passing multiple paths with help of pipe operator, that should hopefully resolve your issue. Please let us know incase you still face the issue. Please find a small example below for your reference.
with:
        dotnet-version: 8.0.x
        cache-dependency-path: |
          './appsettings.Development.json'
          './appsettings.json'

**Comment by Denyyyys** [comment]
Hello @suyashgaonkar. 

Thank you for your response!

Unfortunatelly, your solution didn't work for me. When I use the same configuration as you showed, it implicitly sets _cache: false_, which means the cache is not used. In this case, everything works as expected, but I want to use the cache. When I try to add _cache: true_ and use the pipe operator like this:
        dotnet-version: 8.x
        cache: true
        cache-dependency-path: |
          './backend/WebServer'
          './tetBackend'

I see the following error: **Error: Some specified paths were not resolved, unable to cache dependencies**. You can see my job logs for this configuration using that [link](https://github.com/Denyyyys/LangLearner/actions/runs/10161665378/job/28100627697). My repository in that state is available under this [link](https://github.com/Denyyyys/LangLearner/tree/ad018241994eb58c7cf0e7ee3021a4cfde9b5f33), so feel free to use this repo.

Even if you figure out how to use the cache with package.lock.json files from ./testBackend and ./backend/WebServer paths, the build pipeline fails during the test phase.

Any help you can provide would be greatly appreciated!

**Comment by suyashgaonkar** [comment]
Hi @Dennyyys, the way cache dependency works is that builds and restore the cache depending on the changes found in packages.lock.json file, hence we need to pass the absoloute path to the package.lock.json file in the cache-dependency-path.You can check the official documentation on the same in the following url: https://github.com/actions/setup-dotnet?tab=readme-ov-file#caching-nuget-packages. 
We did fork your repo to work upon the issue and attached screenshot has the result with suggested solution.

![image](https://github.com/user-attachments/assets/a3eff56a-caa2-41eb-9a54-2e049cf845ff)












Another alternative that we can suggest to help you with caching dependecy is actions/cache Github action. You can find detailed documentation and examples related to caching in the follwing links : 
https://github.com/actions/cache 
https://github.com/actions/cache/blob/main/examples.md#c---nuget

**Comment by suyashgaonkar** [comment]
Hi @Denyyyys, We are awaiting for your response on the issue. Please let us know if we can close this issue if there are no further queries.

**Comment by Denyyyys** [comment]
Hi @suyashgaonkar,

Thanks for your detailed response! I tried your solution, and it works for me. I probably should have read through the documentation more thoroughly to better understand how cache dependency works in .NET. Sorry for the late response - I couldn't reply earlier.

You can go ahead and close this issue :)
