### ISSUE TITLE
actions/setup-dotnet@v1 with dotnet-version fails very cryptically 

### ISSUE THREAD

**Issue by smithago** [actions/setup-dotnet#54]
I had a github workflow action like below

- name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0

You can try it, It kept failing cryptically with an error like  

##[error]Node run failed with exit code 1

I could not figure out why it was failing, there was no info in the raw log either. 

Finally after several trial and error, I figured it was related to version and I changed to version to 3.0.100 and it worked.

Please fix the error message to more actionable ones.

**Comment by ZEisinger** [comment]
Thanks, this will be good to update. We are making changes to the way installation occurs and should verify this once #10 and #14 are addressed.

**Comment by ShubhamSureWash** [comment]
what 
dotnet-version=???? to use, 
I want to use ,NET froamwork 4.5, I tried all possible combination every time getting exception, I want to use it for Windows-latest

**Comment by ZEisinger** [comment]
@ShubhamSureWash This action is for installing .NET Core. For the hosted runner you are using, 4.8 is installed on the agent. https://github.com/microsoft/azure-pipelines-image-generation/blob/releases/vs2019/20191202/images/win/Vs2019-Server2019-Readme.md#net-48

**Comment by RehanSaeed** [comment]
Any updates? 3.1.102 is out and this task fails to install it.

**Comment by ZEisinger** [comment]
Error logs now include the message: `Could not find/download: ".NET Core SDK" with version = 4.5`
