### ISSUE TITLE
No new releases to the marketplace since v1.0.0

### ISSUE THREAD

**Issue by Jakst** [actions/setup-dotnet#57]
When I look at https://github.com/marketplace/actions/setup-dotnet-for-use-with-actions there is only one version, v1.0.0. Looking at the source code in this repository however, there have been several subsequent releases, with the latest being v1.3.0. Is something off here? Do you not release updates to the marketplace?

The reason I'm digging into this is because I want to use a GPR source-url like it is documented here, but I can see not proof that my action actually runs the authentication flow by creating a new nuget.package file like it should. I've run the source code for this action locally, and then it works like it should by creating another nuget.package. So my suspicion is that the code simply is not included in the public verison in the marketplace when using `actions/setup-dotnet@v1`.

**Comment by ZEisinger** [comment]
The latest GPR updates are not in v1.3.0 yet, we are planning to release them soon and publish the latest version to the marketplace at the same time.

**Comment by Jakst** [comment]
Okay, so the documentation in README is ahead of the latest release? Because that is kind of confusing. I wouldn't know where to look for the documentation for the current release.

**Comment by ZEisinger** [comment]
Thanks for filing this issue. Publishing to the marketplace got delayed by holidays, but is now updated.
