### ISSUE TITLE
.dotnet/tools is not on path

### ISSUE THREAD

**Issue by casz** [actions/setup-dotnet#69]
Trying to install codecov.tool and use it appears that `.dotnet/tool` is not on path.

https://github.com/casz/GitLabApiClient/blob/b295527722130004e1c2125d2e8055f68721d41c/.github/workflows/ci.yml
https://github.com/nmklotas/GitLabApiClient/blob/b295527722130004e1c2125d2e8055f68721d41c/test.ps1

https://github.com/nmklotas/GitLabApiClient/pull/100/checks?check_run_id=359089103#step:7:486

**Comment by casz** [comment]
further debugging shows that `.dotnet/tools` is definitely not on path and is definitely not handled by `setup-dotnet`

Looks like `.dotnet/tools` is on `$HOME/.dotnet/tools` basically the default. I wonder if that is what we want if we wanted to do some sort of caching of dotnet tools?

**Comment by casz** [comment]
Here is my repro: https://github.com/casz/setup-dotnet-global-tool-repro

**Comment by casz** [comment]
Working on a immediate fix.

However I have questions I'd like answered.

Do we cache the installed tools?
Do we modify the `DOTNET_CLI_HOME` for easier caching?

Are we okay with using `$HOME/.dotnet/tools`

I have question for `actions/core` `core.addPath` seems to only support prepend to path. However in our case we most likely want to append to Path.

**Comment by bryanmacfarlane** [comment]
If it's the globally installed tools in the virtual machine, isn't this really an issue in https://github.com/actions/virtual-environments ?  In other words, if I didn't use the setup-dotnet action and dotnettools are installed on the image, shouldn't it be in the path?

**Comment by ZEisinger** [comment]
As this action currently works, the dotnet install does not happen to the global location. I agree with Bryan that this should be handled by the virtual-environments team, if someone were to use a self-hosted agent we shouldn't add a path to where we think tools could be present and would leave it up to the machine or workflow. This action does add the path of the install location that we use.

It seems this was agreed on the PR, and I am closing this and the PR. Feel free to reopen as needed.

**Comment by ZEisinger** [comment]
Also linking to the issue against virtual-environments: https://github.com/actions/virtual-environments/issues/213

**Comment by casz** [comment]
For anyone finding this issue:

I been using my branch as an workaround while waiting for fixes on the virtual environments.

```yaml
      - name: Setup dotnet
        uses: casz/setup-dotnet@fix/dotnet-global-tool
        with:
          dotnet-version: '3.1.100'
```
https://github.com/nmklotas/GitLabApiClient/blob/e133f248d2739fcd1ed45b2ebf4b9d94a7dc5295/.github/workflows/ci.yml#L22-L25
