### ISSUE TITLE
Support .NET 5

### ISSUE THREAD

**Issue by 9034725985** [actions/setup-dotnet#80]
I am trying to get github actions to work with .NET 5 but without any success 

https://github.com/kusl/mydotnet/actions/ 

There's some hint over at https://github.com/dotnet/cli , 

> This repo has been merged into https://github.com/dotnet/sdk. Previous releases (prior to .NET 5) will still be serviced out of this repo.

see also https://github.com/dotnet/announcements/issues/119

**Comment by safern** [comment]
Answered here: https://github.com/dotnet/runtime/issues/34699#issuecomment-611094892

It seems there is support, you're just passing the wrong dotnet-version of the SDK.

**Comment by 9034725985** [comment]
fixed thank you @safern

**Comment by jcapellman** [comment]
On a similar note, what is the suggested method for getting WPF .NET 5 applications built given the .NET 5 SDK is version 5.0.100-preview.3.20216.6 and the Windows Desktop version is 5.0.0-preview.3.20214.2.  

I got .NET 5 pulling down successfully, but errors when trying to build my WPF application: "The framework 'Microsoft.WindowsDesktop.App', version '5.0.0-preview.3.20214.2' was not found."

**Comment by Corniel** [comment]
Might be worth using this version in the README.md?
