### ISSUE TITLE
Regularly the job could not download dotnet sdk 

### ISSUE THREAD

**Issue by nicolas63** [actions/setup-dotnet#86]
Could Not Download https://download.visualstudio.microsoft.com/download/pr/d731f991-8e68-4c7c-8ea0-fad5605b077a/49497b5420eecbd905158d86d738af64/dotnet-sdk-3.1.100-linux-x64.tar.gz {"code":"CERT_HAS_EXPIRED"}

**Comment by timheuer** [comment]
@nicolas63 do you have a log we cold look at on a repo that failed this action that is public?

**Comment by nicolas63** [comment]
yes for example : https://github.com/jhipster/jhipster-dotnetcore/runs/636212810?check_suite_focus=true
When i re-run the job in most case the task is success

**Comment by timheuer** [comment]
This is weird, thanks.  Looks like we've got some convos going on it.  The cert definitely is valid :-)

**Comment by nicolas63** [comment]
Nice 😃

**Comment by nicolas63** [comment]
Have you other repository with this error ?

**Comment by timheuer** [comment]
I have not

-th
________________________________

**Comment by martincostello** [comment]
I can't share the link to the job because it's in a private repo, but I just had this happen to me:

```
Current runner version: '2.169.1'
Operating System
  Microsoft Windows Server 2019
  10.0.17763
  Datacenter
Virtual Environment
  Environment: windows-2019
  Version: 20200426.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20200426.1/images/win/Windows2019-Readme.md
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 'actions/setup-dotnet@v1'
Download action repository 'actions/upload-artifact@v1'

Run actions/setup-dotnet@v1
  with:
    dotnet-version: 3.1.201
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'd:\a\_actions\actions\setup-dotnet\v1\externals\get-os-platform.ps1'"
Primary:win-x64
Checking tool cache
Getting a download url 3.1.201
Could Not Download https://download.visualstudio.microsoft.com/download/pr/adeab8b1-1c44-41b2-b12a-156442f307e9/65ebf805366410c63edeb06e53959383/dotnet-sdk-3.1.201-win-x64.zip {"code":"CERT_HAS_EXPIRED"}
```

**Comment by fzumstein** [comment]
Here's another case: https://github.com/xlwings/xlwings/runs/658863994?check_suite_focus=true

**Comment by Happypig375** [comment]
Here's my case:
https://github.com/verybadcat/CSharpMath/runs/688727898?check_suite_focus=true

**Comment by ZEisinger** [comment]
Thanks for the additional reports. The issue was identified and resolved in the last couple hours. If there are further problems, please reopen this issue.

**Comment by timheuer** [comment]
@ZEisinger can you share the issue cause/resolution?
