### ISSUE TITLE
add option to remove welcome message

### ISSUE THREAD

**Issue by piot** [actions/setup-dotnet#91]
When running dotnet for the first time, it spits out an annoying welcome message. That is not useful for ci builds.

```Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.101

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
```

**Comment by ZEisinger** [comment]
Thanks, I added a PR for surfacing the environment variable in the README. While I think suppressing the version message by default might be useful, I don't want to hide the telemetry message by default and the nologo flag hides both.
